import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'content-type':'application/json'}});
const env=(k:string)=>{const v=Deno.env.get(k);if(!v)throw new Error(`Missing secret ${k}`);return v};
const b64u=(b:Uint8Array)=>btoa(String.fromCharCode(...b)).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
function pemBytes(pem:string){const x=pem.replace(/-----[^-]+-----/g,'').replace(/\s/g,'');return Uint8Array.from(atob(x),c=>c.charCodeAt(0))}
async function signLicense(payload:string){const key=await crypto.subtle.importKey('pkcs8',pemBytes(env('SOLVEX_LICENSE_PRIVATE_KEY')),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const data=new TextEncoder().encode(payload);const sig=new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,data));return `${b64u(data)}.${b64u(sig)}`}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const url=env('SUPABASE_URL'),anon=env('SUPABASE_ANON_KEY'),service=env('SUPABASE_SERVICE_ROLE_KEY');
 const auth=req.headers.get('authorization')||'';if(!auth.startsWith('Bearer '))return json({error:'Unauthorized'},401);
 const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
 const {data:{user},error:ue}=await userClient.auth.getUser();if(ue||!user)return json({error:'Unauthorized'},401);
 const body=await req.json(),action=body.action;
 const {data:po}=await admin.from('platform_owners').select('user_id').eq('user_id',user.id).eq('active',true).maybeSingle();const owner=!!po;
 const tenantAdmin=async(orgId:string)=>{const {data}=await admin.from('memberships').select('id').eq('organization_id',orgId).eq('user_id',user.id).eq('active',true).in('role',['tenant_admin','platform_owner']).maybeSingle();return !!data};
 if(action==='owner_bootstrap'){if(!owner)return json({error:'Forbidden'},403);return json({email:user.email,user_id:user.id})}
 if(action==='owner_dashboard'){if(!owner)return json({error:'Forbidden'},403);
   const [{data:orgs},{data:subs},{data:lic},{data:inst},{data:plans}]=await Promise.all([admin.from('organizations').select('*').order('created_at',{ascending:false}),admin.from('subscriptions').select('*').order('starts_at',{ascending:false}),admin.from('license_issuances').select('*').order('issued_at',{ascending:false}).limit(1000),admin.from('app_installations').select('*'),admin.from('plans').select('*')]);
   const pm=new Map((plans||[]).map((p:any)=>[p.code,p]));const latest=new Map();for(const s of subs||[])if(!latest.has(s.organization_id))latest.set(s.organization_id,s);
   const organizations=(orgs||[]).map((o:any)=>{const s=latest.get(o.id),p=s?pm.get(s.plan_code):null;return {...o,plan_name:p?.name||null,plan_code:s?.plan_code||null}});
   const om=new Map(organizations.map((o:any)=>[o.id,o]));const licenses=(lic||[]).map((l:any)=>{const o=om.get(l.organization_id);return {...l,trade_name:o?.trade_name||'—',owner_name:o?.legal_name||o?.trade_name||'—',phone:o?.phone||''}});const mrr=(subs||[]).filter((s:any)=>s.status==='active'&&s.plan_code==='monthly').reduce((a:number,s:any)=>a+Number(s.amount_cop||0),0);
   return json({metrics:{clients:organizations.length,active_licenses:licenses.filter((x:any)=>!x.revoked_at&&(!x.expires_at||new Date(x.expires_at)>new Date())).length,active_devices:(inst||[]).filter((x:any)=>x.active).length,mrr_cop:mrr},organizations,licenses})}
 if(action==='create_owner_customer'){if(!owner)return json({error:'Forbidden'},403);const name=String(body.owner_name||'').trim(),phone=String(body.phone||'').replace(/[^0-9+]/g,'').trim();if(!name||!phone)return json({error:'Nombre del propietario y celular son obligatorios'},400);const {data:o,error:oe}=await admin.from('organizations').insert({legal_name:name,trade_name:name,phone,status:'active'}).select().single();if(oe)throw oe;await admin.from('subscriptions').insert({organization_id:o.id,plan_code:'trial',status:'trialing',starts_at:new Date().toISOString(),ends_at:new Date(Date.now()+15*86400000).toISOString()});return json({organization:o})}
 if(action==='create_organization'){if(!owner)return json({error:'Forbidden'},403);const legal=String(body.legal_name||'').trim(),trade=String(body.trade_name||'').trim(),adminEmail=String(body.admin_email||'').trim().toLowerCase();if(!legal||!trade||!adminEmail)return json({error:'Datos obligatorios incompletos'},400);
   const {data:o,error:oe}=await admin.from('organizations').insert({legal_name:legal,trade_name:trade,tax_id:body.tax_id||null,email:body.email||null,phone:body.phone||null,status:'active'}).select().single();if(oe)throw oe;
   const plan=body.plan_code||'trial';const days=plan==='trial'?15:plan==='monthly'?31:plan==='annual'?366:null;const ends=days?new Date(Date.now()+days*86400000).toISOString():null;await admin.from('subscriptions').insert({organization_id:o.id,plan_code:plan,status:plan==='trial'?'trialing':'active',starts_at:new Date().toISOString(),ends_at:ends});
   const {data:inv,error:ie}=await admin.auth.admin.inviteUserByEmail(adminEmail,{data:{full_name:body.admin_name||trade,organization_id:o.id,role:'tenant_admin'}});if(ie)throw ie;const uid=inv.user.id;await admin.from('profiles').upsert({user_id:uid,full_name:body.admin_name||trade,active:true});await admin.from('memberships').upsert({organization_id:o.id,user_id:uid,role:'tenant_admin',active:true},{onConflict:'organization_id,user_id'});return json({organization:o,admin_user_id:uid})}
 if(action==='invite_user'){const orgId=String(body.organization_id||'');if(!owner&&!(await tenantAdmin(orgId)))return json({error:'Forbidden'},403);const email=String(body.email||'').trim().toLowerCase(),name=String(body.full_name||'').trim(),role=String(body.role||'viewer');if(!email||!name)return json({error:'Nombre y correo son obligatorios'},400);const allowed=['tenant_admin','auditor','supervisor','operator','cashier','viewer'];if(!allowed.includes(role))return json({error:'Rol inválido'},400);const {data:inv,error}=await admin.auth.admin.inviteUserByEmail(email,{data:{full_name:name,organization_id:orgId,role}});if(error)throw error;await admin.from('profiles').upsert({user_id:inv.user.id,full_name:name,active:true});await admin.from('memberships').upsert({organization_id:orgId,user_id:inv.user.id,role,active:true},{onConflict:'organization_id,user_id'});return json({user_id:inv.user.id})}
 if(action==='issue_license'){if(!owner)return json({error:'Forbidden'},403);const orgId=String(body.organization_id||''),device=String(body.device_id||'').trim(),plan=String(body.plan_code||'annual');if(!orgId||!device)return json({error:'Cliente y ANDROID_ID son obligatorios'},400);const {data:o}=await admin.from('organizations').select('trade_name,legal_name,phone').eq('id',orgId).single();const now=Math.floor(Date.now()/1000);let exp=0;if(plan==='monthly')exp=now+31*86400;else if(plan==='annual')exp=now+366*86400;else if(plan==='custom'){const d=Math.max(1,Number(body.days||1));exp=now+d*86400}else if(plan!=='lifetime')return json({error:'Plan inválido'},400);const licenseId='LIC-'+crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase();const payload=`SVX1|${licenseId}|${(o?.trade_name||'CLIENTE').replaceAll('|','-')}|${device.replaceAll('|','-')}|${plan}|${exp}`;const key=await signLicense(payload);const {data:inst,error:ix}=await admin.from('app_installations').upsert({organization_id:orgId,device_id:device,label:body.label||null,platform:'android',active:true},{onConflict:'organization_id,device_id'}).select().single();if(ix)throw ix;const expires=exp?new Date(exp*1000).toISOString():null;await admin.from('license_issuances').insert({license_id:licenseId,organization_id:orgId,installation_id:inst.id,device_id:device,plan_code:plan,issued_to:o?.trade_name||'CLIENTE',license_key:key,expires_at:expires,metadata:{issued_by:user.id,phone:o?.phone||'',owner_name:o?.legal_name||o?.trade_name||''}});return json({license_id:licenseId,license_key:key,expires_at:expires,phone:o?.phone||'',owner_name:o?.legal_name||o?.trade_name||''})}
 if(action==='revoke_license'){if(!owner)return json({error:'Forbidden'},403);const {error}=await admin.from('license_issuances').update({revoked_at:new Date().toISOString(),revoked_by:user.id}).eq('license_id',body.license_id);if(error)throw error;return json({ok:true})}
 return json({error:'Unknown action'},400);
}catch(e){console.error(e);return json({error:e?.message||'Internal error'},500)}});