import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const cors={
  'Access-Control-Allow-Origin':'*',
  'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type',
};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'content-type':'application/json'}});
const env=(n:string)=>{const v=Deno.env.get(n);if(!v)throw new Error(`Missing environment value ${n}`);return v};
const clean=(v:unknown)=>String(v??'').trim();
const phone=(v:unknown)=>clean(v).replace(/[^0-9+]/g,'');
const isoDate=(d=new Date())=>d.toISOString().slice(0,10);
const addDays=(days:number)=>{const d=new Date();d.setUTCDate(d.getUTCDate()+days);return isoDate(d)};
const token=()=>{const b=crypto.getRandomValues(new Uint8Array(32));return 'SVX2.'+btoa(String.fromCharCode(...b)).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')};
const OWNER_EMAILS=new Set(['jbernalcristancho82@hotmail.com']);
const TYPES=['carro','moto','bicicleta','patineta'];
const DEFAULT_RATES:any={carro:{min:200,dia:22000,mes:180000},moto:{min:140,dia:11000,mes:90000},bicicleta:{min:10,dia:3000,mes:35000},patineta:{min:10,dia:3000,mes:35000}};
const DEFAULT_METHODS=[
 ['efectivo','Efectivo en caja',true,10],['nequi','Nequi',true,20],['daviplata','Daviplata',true,30],['breb','Bre-B',true,40],['pse','PSE / botón de pago',false,50],['transferencia','Transferencia bancaria',false,60],['qr','Código QR Bancolombia',false,70]
];

Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 try{
  const url=env('SUPABASE_URL'),anon=env('SUPABASE_ANON_KEY'),service=env('SUPABASE_SERVICE_ROLE_KEY');
  const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
  const body=await req.json();const action=clean(body.action);

  const validateLicense=async(licenseKey:string,deviceId:string)=>{
   if(!licenseKey||!deviceId)throw Object.assign(new Error('Licencia e ID del dispositivo son obligatorios'),{status:400});
   const {data:lic,error}=await admin.from('licencias').select('id,cliente_id,clave,tipo,estado,fecha_vencimiento,dias_gracia,device_id,app_target,max_usuarios,max_sedes,clientes(nombre_negocio,contacto,celular,email)').eq('clave',licenseKey).maybeSingle();
   if(error)throw error;if(!lic)throw Object.assign(new Error('Licencia no encontrada'),{status:404});if(lic.estado!=='activa')throw Object.assign(new Error('Licencia suspendida o cancelada'),{status:403});if(clean(lic.device_id)!==deviceId)throw Object.assign(new Error('La licencia pertenece a otro dispositivo'),{status:403});
   const limit=new Date(`${lic.fecha_vencimiento}T23:59:59Z`);limit.setUTCDate(limit.getUTCDate()+Number(lic.dias_gracia||0));if(Date.now()>limit.getTime())throw Object.assign(new Error('Licencia vencida'),{status:403});return lic as any;
  };
  const primarySite=async(clienteId:string)=>{let {data:s}=await admin.from('sedes').select('*').eq('cliente_id',clienteId).eq('activa',true).order('created_at').limit(1).maybeSingle();if(!s){const {data:ns,error}=await admin.from('sedes').insert({cliente_id:clienteId,nombre:'Sede principal',codigo:'PRINCIPAL'}).select().single();if(error)throw error;s=ns}return s as any};
  const seedSite=async(clienteId:string,sedeId:string,name:string,cell='')=>{
   await admin.from('configuracion_parqueadero').upsert({cliente_id:clienteId,sede_id:sedeId,nombre:name,telefono:cell},{onConflict:'sede_id',ignoreDuplicates:true});
   for(const t of TYPES){const r=DEFAULT_RATES[t];await admin.from('tarifas_parqueadero').upsert({cliente_id:clienteId,sede_id:sedeId,tipo_vehiculo:t,valor_minuto:r.min,tope_dia:r.dia,mensualidad:r.mes},{onConflict:'sede_id,tipo_vehiculo',ignoreDuplicates:true})}
   for(const [codigo,nombre,activo,orden] of DEFAULT_METHODS){await admin.from('medios_pago_parqueadero').upsert({cliente_id:clienteId,sede_id:sedeId,codigo,nombre,activo,orden},{onConflict:'sede_id,codigo',ignoreDuplicates:true})}
  };
  const findOrInvite=async(email:string,metadata:any={})=>{
   const normalized=email.toLowerCase();let found:any=null;
   for(let page=1;page<=10&&!found;page++){const {data,error}=await admin.auth.admin.listUsers({page,perPage:100});if(error)throw error;found=(data.users||[]).find((u:any)=>String(u.email||'').toLowerCase()===normalized);if((data.users||[]).length<100)break}
   if(found)return found;
   const invite=await admin.auth.admin.inviteUserByEmail(normalized,{data:metadata});if(invite.error)throw invite.error;return invite.data.user;
  };

  if(action==='activate_license'||action==='device_bootstrap'){
   const licenseKey=clean(body.license_key),deviceId=clean(body.device_id),lic=await validateLicense(licenseKey,deviceId);const customer:any=Array.isArray(lic.clientes)?lic.clientes[0]:lic.clientes;const site=await primarySite(lic.cliente_id);await seedSite(lic.cliente_id,site.id,customer?.nombre_negocio||'Parqueadero',customer?.celular||'');const dtype=deviceId.toUpperCase().startsWith('WEB-')?'browser':'android';
   await admin.from('dispositivos').upsert({cliente_id:lic.cliente_id,sede_id:site.id,licencia_id:lic.id,device_id:deviceId,tipo:dtype,nombre:dtype==='browser'?'PARKSOLVEX Web':'PARKOPS Android',estado:'activo',last_seen_at:new Date().toISOString(),app_version:clean(body.app_version)||'1.5.3'},{onConflict:'cliente_id,device_id'});
   if(action==='activate_license')return json({ok:true,license_id:lic.id,plan_code:lic.tipo,expires_at:lic.fecha_vencimiento,customer_name:customer?.nombre_negocio||customer?.contacto||'CLIENTE',organization_id:lic.cliente_id,sede_id:site.id,app_target:lic.app_target});
   const [{data:cfg},{data:rates},{data:methods}]=await Promise.all([admin.from('configuracion_parqueadero').select('*').eq('sede_id',site.id).maybeSingle(),admin.from('tarifas_parqueadero').select('*').eq('sede_id',site.id).order('tipo_vehiculo'),admin.from('medios_pago_parqueadero').select('*').eq('sede_id',site.id).order('orden')]);return json({ok:true,organization:{id:lic.cliente_id,name:customer?.nombre_negocio||'CLIENTE'},site,license:{id:lic.id,plan:lic.tipo,expires_at:lic.fecha_vencimiento},config:cfg,rates:rates||[],payment_methods:methods||[]});
  }

  if(action==='sync_push'){
   const lic=await validateLicense(clean(body.license_key),clean(body.device_id)),site=await primarySite(lic.cliente_id),deviceId=clean(body.device_id),payload=body.payload||{};
   if(payload.cfg){const c=payload.cfg;await admin.from('configuracion_parqueadero').upsert({cliente_id:lic.cliente_id,sede_id:site.id,nombre:clean(c.nombre)||'Parqueadero',nit:clean(c.nit)||null,direccion:clean(c.direccion)||null,telefono:clean(c.telefono)||null,prefijo:clean(c.prefijo)||'PQ-',consecutivo:Number(c.consecutivo||1001),gracia_min:Number(c.gracia||0),redondeo:Number(c.redondeo||50),sello_oro:!!c.selloOro,recarga:c.recarga||{},plantilla_ingreso:c.pIngreso||null,plantilla_pago:c.pPago||null,raw_cfg:c},{onConflict:'sede_id'});if(Array.isArray(c.medios))for(let i=0;i<c.medios.length;i++){const m=c.medios[i];await admin.from('medios_pago_parqueadero').upsert({cliente_id:lic.cliente_id,sede_id:site.id,codigo:clean(m.id)||`m${i}`,nombre:clean(m.n)||clean(m.id),activo:m.on!==false,dato:clean(m.dato)||null,enlace:clean(m.link)||null,app_package:clean(m.app)||null,key_type:clean(m.keyType)||null,holder:clean(m.holder)||null,orden:(i+1)*10,metadata:m},{onConflict:'sede_id,codigo'})}}
   if(payload.tarifas&&typeof payload.tarifas==='object')for(const t of TYPES){const r=payload.tarifas[t];if(r)await admin.from('tarifas_parqueadero').upsert({cliente_id:lic.cliente_id,sede_id:site.id,tipo_vehiculo:t,valor_minuto:Number(r.min||0),tope_dia:Number(r.dia||0),mensualidad:Number(r.mes||0),raw_tarifa:r},{onConflict:'sede_id,tipo_vehiculo'})}
   if(Array.isArray(payload.clientes))for(const c of payload.clientes){const placa=clean(c.placa).toUpperCase();if(!placa)continue;await admin.from('clientes_parqueadero').upsert({cliente_id:lic.cliente_id,sede_id:site.id,placa,nombre:clean(c.nombre)||null,celular:clean(c.celular)||null,tipo_vehiculo:TYPES.includes(clean(c.tipo))?clean(c.tipo):null,metadata:c},{onConflict:'sede_id,placa'})}
   if(Array.isArray(payload.mensualidades))for(const m of payload.mensualidades){const placa=clean(m.placa).toUpperCase();if(!placa||!m.desde||!m.hasta)continue;const existing=await admin.from('mensualidades_parqueadero').select('id').eq('sede_id',site.id).eq('placa',placa).eq('desde',m.desde).eq('hasta',m.hasta).maybeSingle();const row={cliente_id:lic.cliente_id,sede_id:site.id,placa,desde:m.desde,hasta:m.hasta,valor:Number(m.valor||0),incluye_recarga:!!m.incluyeRecarga,tipo_vehiculo:clean(m.tipo)||null,nombre:clean(m.nombre)||null,celular:clean(m.celular)||null,metadata:m};if(existing.data)await admin.from('mensualidades_parqueadero').update(row).eq('id',existing.data.id);else await admin.from('mensualidades_parqueadero').insert(row)}
   if(Array.isArray(payload.ingresos))for(const r of payload.ingresos){if(!r.recibo||!r.placa||!r.entrada)continue;const row:any={cliente_id:lic.cliente_id,sede_id:site.id,local_id:clean(r.id)||null,recibo:clean(r.recibo),placa:clean(r.placa).toUpperCase(),tipo_vehiculo:TYPES.includes(clean(r.tipo))?clean(r.tipo):'carro',electrico:!!r.electrico,kwh:Number(r.kwh||0),nombre:clean(r.nombre)||null,celular:clean(r.celular)||null,observaciones:clean(r.obs)||null,entrada_at:new Date(Number(r.entrada)).toISOString(),salida_at:r.salida?new Date(Number(r.salida)).toISOString():null,valor_total:r.valor==null?null:Number(r.valor),valor_parqueo:r.valorParqueo==null?null:Number(r.valorParqueo),valor_recarga:r.valorRecarga==null?null:Number(r.valorRecarga),medio_pago:clean(r.medio)||null,operario:clean(r.operario)||null,estado:r.salida?'salida':'en_patio',sync_source:'license',device_id:deviceId,raw_record:r};await admin.from('ingresos_parqueadero').upsert(row,{onConflict:'sede_id,recibo'})}
   const now=new Date().toISOString();await admin.from('sync_state').upsert({cliente_id:lic.cliente_id,sede_id:site.id,device_id:deviceId,last_push_at:now,cursor_at:now,app_version:clean(body.app_version)||'1.5.3'},{onConflict:'cliente_id,device_id'});await admin.from('auditoria_parksolvex').insert({cliente_id:lic.cliente_id,sede_id:site.id,device_id:deviceId,accion:'sync_push',entidad:'device',entidad_id:deviceId,payload:{counts:{clientes:payload.clientes?.length||0,ingresos:payload.ingresos?.length||0,mensualidades:payload.mensualidades?.length||0}}});return json({ok:true,synced_at:now});
  }

  if(action==='sync_pull'){
   const lic=await validateLicense(clean(body.license_key),clean(body.device_id)),site=await primarySite(lic.cliente_id),since=clean(body.since);const q=(table:string)=>{let x:any=admin.from(table).select('*').eq('sede_id',site.id);if(since)x=x.gt('updated_at',since);return x};const [cfg,rates,methods,customers,monthly,entries]=await Promise.all([q('configuracion_parqueadero'),q('tarifas_parqueadero'),q('medios_pago_parqueadero'),q('clientes_parqueadero'),q('mensualidades_parqueadero'),q('ingresos_parqueadero')]);const now=new Date().toISOString();await admin.from('sync_state').upsert({cliente_id:lic.cliente_id,sede_id:site.id,device_id:clean(body.device_id),last_pull_at:now,cursor_at:now,app_version:clean(body.app_version)||'1.5.3'},{onConflict:'cliente_id,device_id'});return json({ok:true,cursor:now,config:cfg.data?.[0]||null,rates:rates.data||[],payment_methods:methods.data||[],customers:customers.data||[],monthly:monthly.data||[],entries:entries.data||[]});
  }

  const auth=req.headers.get('authorization')||'';if(!auth.startsWith('Bearer '))return json({error:'Unauthorized'},401);const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user},error:userError}=await userClient.auth.getUser();if(userError||!user)return json({error:'Unauthorized'},401);
  if(action==='claim_owner_account'){const email=clean(user.email).toLowerCase();if(!OWNER_EMAILS.has(email))return json({error:'Este correo no está autorizado como propietario'},403);const {error}=await admin.from('platform_owners').upsert({user_id:user.id,active:true},{onConflict:'user_id'});if(error)throw error;return json({ok:true,email,user_id:user.id})}
  const {data:platformOwner}=await admin.from('platform_owners').select('user_id').eq('user_id',user.id).eq('active',true).maybeSingle();
  const memberships=async()=>{if(platformOwner){const {data,error}=await admin.from('clientes').select('id,nombre_negocio,contacto,celular,email,estado,sedes(id,nombre,codigo,activa)').order('creado_en',{ascending:false});if(error)throw error;return(data||[]).map((c:any)=>({cliente_id:c.id,rol:'platform_owner',nombre:user.email,activo:true,clientes:c,sedes:c.sedes||[]}))}const {data,error}=await admin.from('usuario_organizaciones').select('cliente_id,rol,nombre,celular,activo,clientes(id,nombre_negocio,contacto,celular,email,estado),sedes(id,nombre,codigo,activa)').eq('user_id',user.id).eq('activo',true);if(error)throw error;return data||[]};
  const requireOrg=async(orgId:string,roles:string[])=>{if(platformOwner)return true;const {data}=await admin.from('usuario_organizaciones').select('rol').eq('cliente_id',orgId).eq('user_id',user.id).eq('activo',true).maybeSingle();if(!data||!roles.includes(data.rol))throw Object.assign(new Error('Forbidden'),{status:403});return true};

  if(action==='owner_bootstrap'||action==='tenant_bootstrap')return json({email:user.email,user_id:user.id,platform_owner:!!platformOwner,memberships:await memberships()});
  if(action==='owner_dashboard'){
   if(!platformOwner)return json({error:'Forbidden'},403);const [{data:customers,error:ce},{data:licenseRows,error:le},{data:deviceRows}]=await Promise.all([admin.from('clientes').select('*').order('creado_en',{ascending:false}),admin.from('licencias').select('*').order('creado_en',{ascending:false}).limit(5000),admin.from('dispositivos').select('*')]);if(ce)throw ce;if(le)throw le;const organizations=(customers||[]).map((c:any)=>({id:c.id,trade_name:c.nombre_negocio,legal_name:c.contacto||c.nombre_negocio,phone:c.celular||'',email:c.email||'',status:c.estado,created_at:c.creado_en}));const map=new Map(organizations.map((o:any)=>[o.id,o]));const planMap:any={mensual:'monthly',anual:'annual',vitalicia:'lifetime',personalizada:'custom',dia:'custom',alquiler:'custom'};const licenses=(licenseRows||[]).map((l:any)=>{const c:any=map.get(l.cliente_id);return{organization_id:l.cliente_id,license_id:l.id,device_id:l.device_id||'',app_target:l.app_target,plan_code:planMap[l.tipo]||l.tipo,license_key:l.clave,status:l.estado,expires_at:l.fecha_vencimiento,trade_name:c?.trade_name||'—',owner_name:c?.legal_name||c?.trade_name||'—',phone:c?.phone||''}});const today=isoDate();const active=licenses.filter((l:any)=>l.status==='activa'&&l.expires_at>=today);return json({metrics:{clients:organizations.length,active_licenses:active.length,active_devices:(deviceRows||[]).filter((d:any)=>d.estado==='activo').length,mrr_cop:0},organizations,licenses,devices:deviceRows||[]});
  }
  if(action==='create_owner_customer'){
   if(!platformOwner)return json({error:'Forbidden'},403);const name=clean(body.owner_name||body.trade_name),p=phone(body.phone),email=clean(body.email).toLowerCase()||null;if(!name||!p)return json({error:'Nombre del propietario y celular son obligatorios'},400);const {data:c,error}=await admin.from('clientes').insert({nombre_negocio:name,contacto:name,celular:p,email}).select().single();if(error)throw error;const site=await primarySite(c.id);await admin.from('sedes').update({nombre:clean(body.site_name)||name,direccion:clean(body.address)||null,telefono:p}).eq('id',site.id);await seedSite(c.id,site.id,name,p);let owner_user_id=null;if(email&&body.invite_owner!==false){const u=await findOrInvite(email,{parksolvex_org:c.id,parksolvex_role:'owner',display_name:name});owner_user_id=u.id;await admin.from('usuario_organizaciones').upsert({cliente_id:c.id,user_id:u.id,rol:'owner',nombre:name,celular:p,activo:true},{onConflict:'cliente_id,user_id'})}return json({organization:{id:c.id,trade_name:c.nombre_negocio,legal_name:c.contacto,phone:c.celular,email:c.email||'',created_at:c.creado_en},site,owner_user_id});
  }
  if(action==='issue_license'){
   if(!platformOwner)return json({error:'Forbidden'},403);const customerId=clean(body.organization_id),deviceId=clean(body.device_id),plan=clean(body.plan_code)||'annual';if(!customerId||!deviceId)return json({error:'Cliente e ID del dispositivo/navegador son obligatorios'},400);const {data:c,error:ce}=await admin.from('clientes').select('*').eq('id',customerId).single();if(ce)throw ce;let tipo='',expiry='';if(plan==='monthly'){tipo='mensual';expiry=addDays(31)}else if(plan==='annual'){tipo='anual';expiry=addDays(366)}else if(plan==='lifetime'){tipo='vitalicia';expiry='2099-12-31'}else if(plan==='custom'){const days=Math.max(1,Number(body.days||1));tipo='personalizada';expiry=addDays(days)}else return json({error:'Plan inválido'},400);const target=clean(body.app_target)||(deviceId.toUpperCase().startsWith('WEB-')?'web':'android');const licenseKey=token();const {data:lic,error}=await admin.from('licencias').insert({cliente_id:customerId,clave:licenseKey,tipo,estado:'activa',fecha_inicio:isoDate(),fecha_vencimiento:expiry,dias_gracia:Number(body.grace_days??5),device_id:deviceId,app_target:target,max_usuarios:Number(body.max_users||10),max_sedes:Number(body.max_sites||1),metadata:{issued_by:user.id}}).select().single();if(error)throw error;const site=await primarySite(customerId);await seedSite(customerId,site.id,c.nombre_negocio,c.celular||'');await admin.from('dispositivos').upsert({cliente_id:customerId,sede_id:site.id,licencia_id:lic.id,device_id:deviceId,tipo:target==='web'?'browser':'android',nombre:target==='web'?'PARKSOLVEX Web':'PARKOPS Android',estado:'activo',app_version:'1.5.3'},{onConflict:'cliente_id,device_id'});return json({license_id:lic.id,license_key:licenseKey,expires_at:expiry,phone:c.celular||'',owner_name:c.contacto||c.nombre_negocio||'CLIENTE',app_target:target});
  }
  if(action==='revoke_license'){if(!platformOwner)return json({error:'Forbidden'},403);const id=clean(body.license_id);if(!id)return json({error:'license_id obligatorio'},400);const {data:lic}=await admin.from('licencias').select('cliente_id,device_id').eq('id',id).maybeSingle();const {error}=await admin.from('licencias').update({estado:'cancelada',actualizado_en:new Date().toISOString()}).eq('id',id);if(error)throw error;if(lic?.device_id)await admin.from('dispositivos').update({estado:'revocado'}).eq('cliente_id',lic.cliente_id).eq('device_id',lic.device_id);return json({ok:true})}

  if(action==='tenant_list_users'){const orgId=clean(body.organization_id);await requireOrg(orgId,['owner','admin','supervisor','auditor']);const {data,error}=await admin.from('usuario_organizaciones').select('id,cliente_id,user_id,rol,nombre,celular,activo,created_at,updated_at').eq('cliente_id',orgId).order('created_at');if(error)throw error;const users=[];for(const m of data||[]){const u=await admin.auth.admin.getUserById(m.user_id);users.push({...m,email:u.data.user?.email||''})}return json({users})}
  if(action==='tenant_invite_user'){const orgId=clean(body.organization_id),email=clean(body.email).toLowerCase(),role=clean(body.role)||'operador',name=clean(body.name),cell=phone(body.phone);await requireOrg(orgId,['owner','admin']);if(!email)return json({error:'Correo obligatorio'},400);if(!['admin','supervisor','operador','auditor'].includes(role))return json({error:'Rol inválido'},400);const {data:license}=await admin.from('licencias').select('max_usuarios').eq('cliente_id',orgId).eq('estado','activa').order('creado_en',{ascending:false}).limit(1).maybeSingle();const {count}=await admin.from('usuario_organizaciones').select('*',{count:'exact',head:true}).eq('cliente_id',orgId).eq('activo',true);if(license&&Number(count||0)>=Number(license.max_usuarios||10))return json({error:'Se alcanzó el máximo de usuarios permitido por la licencia'},403);const u=await findOrInvite(email,{parksolvex_org:orgId,parksolvex_role:role,display_name:name});const {error}=await admin.from('usuario_organizaciones').upsert({cliente_id:orgId,user_id:u.id,rol:role,nombre:name||email,celular:cell||null,activo:true},{onConflict:'cliente_id,user_id'});if(error)throw error;return json({ok:true,user_id:u.id,email,role})}
  if(action==='tenant_set_user'){const orgId=clean(body.organization_id),target=clean(body.user_id);await requireOrg(orgId,['owner','admin']);const updates:any={};if(body.role!==undefined){const r=clean(body.role);if(!['admin','supervisor','operador','auditor'].includes(r))return json({error:'Rol inválido'},400);updates.rol=r}if(body.active!==undefined)updates.activo=!!body.active;if(body.name!==undefined)updates.nombre=clean(body.name);if(body.phone!==undefined)updates.celular=phone(body.phone);const {error}=await admin.from('usuario_organizaciones').update(updates).eq('cliente_id',orgId).eq('user_id',target);if(error)throw error;return json({ok:true})}
  if(action==='tenant_create_site'){const orgId=clean(body.organization_id);await requireOrg(orgId,['owner','admin']);const {data:license}=await admin.from('licencias').select('max_sedes').eq('cliente_id',orgId).eq('estado','activa').order('creado_en',{ascending:false}).limit(1).maybeSingle();const {count}=await admin.from('sedes').select('*',{count:'exact',head:true}).eq('cliente_id',orgId).eq('activa',true);if(license&&Number(count||0)>=Number(license.max_sedes||1))return json({error:'Se alcanzó el máximo de sedes permitido por la licencia'},403);const {data:s,error}=await admin.from('sedes').insert({cliente_id:orgId,nombre:clean(body.name)||'Nueva sede',codigo:clean(body.code)||null,direccion:clean(body.address)||null,telefono:phone(body.phone)||null,nit:clean(body.nit)||null}).select().single();if(error)throw error;await seedSite(orgId,s.id,s.nombre,s.telefono||'');return json({ok:true,site:s})}
  if(action==='tenant_update_site'){const orgId=clean(body.organization_id),siteId=clean(body.site_id);await requireOrg(orgId,['owner','admin']);const updates:any={};for(const [src,dst] of [['name','nombre'],['code','codigo'],['address','direccion'],['phone','telefono'],['nit','nit']] as any){if(body[src]!==undefined)updates[dst]=clean(body[src])||null}if(body.active!==undefined)updates.activa=!!body.active;const {data,error}=await admin.from('sedes').update(updates).eq('id',siteId).eq('cliente_id',orgId).select().single();if(error)throw error;return json({ok:true,site:data})}
  if(action==='tenant_open_turn'){const orgId=clean(body.organization_id),siteId=clean(body.site_id)||(await primarySite(orgId)).id;await requireOrg(orgId,['owner','admin','supervisor','operador']);const {data,error}=await admin.from('turnos_operacion').insert({cliente_id:orgId,sede_id:siteId,user_id:user.id,apertura_caja:Number(body.opening_cash||0),notas:clean(body.notes)||null}).select().single();if(error)throw error;return json({ok:true,shift:data})}
  if(action==='tenant_close_turn'){const orgId=clean(body.organization_id),shiftId=clean(body.shift_id);await requireOrg(orgId,['owner','admin','supervisor','operador']);const {data,error}=await admin.from('turnos_operacion').update({fin_at:new Date().toISOString(),estado:'cerrado',cierre_caja:body.closing_cash==null?null:Number(body.closing_cash),notas:clean(body.notes)||null}).eq('id',shiftId).eq('cliente_id',orgId).select().single();if(error)throw error;return json({ok:true,shift:data})}
  if(action==='tenant_dashboard'){const orgId=clean(body.organization_id);await requireOrg(orgId,['owner','admin','supervisor','operador','auditor']);const siteId=clean(body.site_id)||(await primarySite(orgId)).id;const [entries,monthly,closures,users,config,rates,methods,sites,shifts]=await Promise.all([admin.from('ingresos_parqueadero').select('*').eq('sede_id',siteId).order('entrada_at',{ascending:false}).limit(1000),admin.from('mensualidades_parqueadero').select('*').eq('sede_id',siteId).order('hasta',{ascending:false}).limit(500),admin.from('cierres_caja').select('*').eq('sede_id',siteId).order('fecha_hasta',{ascending:false}).limit(100),admin.from('usuario_organizaciones').select('id,user_id,rol,nombre,celular,activo').eq('cliente_id',orgId),admin.from('configuracion_parqueadero').select('*').eq('sede_id',siteId).maybeSingle(),admin.from('tarifas_parqueadero').select('*').eq('sede_id',siteId),admin.from('medios_pago_parqueadero').select('*').eq('sede_id',siteId).order('orden'),admin.from('sedes').select('*').eq('cliente_id',orgId).order('created_at'),admin.from('turnos_operacion').select('*').eq('sede_id',siteId).order('inicio_at',{ascending:false}).limit(100)]);return json({site_id:siteId,sites:sites.data||[],entries:entries.data||[],monthly:monthly.data||[],closures:closures.data||[],users:users.data||[],shifts:shifts.data||[],config:config.data||null,rates:rates.data||[],payment_methods:methods.data||[]})}
  return json({error:'Unknown action'},400);
 }catch(e:any){console.error(e);return json({error:e instanceof Error?e.message:'Internal error'},Number(e?.status)||500)}
});
