import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const SUPABASE_URL='https://epadzsrfsvckyjugcvpd.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_PxFa4vMqovqCIDOwEsoiBQ_2q2jETc_';
const sb=createClient(SUPABASE_URL,PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const $=s=>document.querySelector(s);let bootstrap=null,dashboard=null,usersData=[];
async function edge(action,extra={}){const {data:{session}}=await sb.auth.getSession();if(!session)throw new Error('Sesión no disponible');const fn=action==='invite_user'?'parksolvex-invite':'parksolvex-admin';const payload=action==='invite_user'?extra:{action,...extra};const r=await fetch(`${SUPABASE_URL}/functions/v1/${fn}`,{method:'POST',headers:{'content-type':'application/json','apikey':PUBLISHABLE_KEY,'authorization':`Bearer ${session.access_token}`},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error||`HTTP ${r.status}`);return d}
function setMsg(id,msg,ok=false){const e=$(id);if(!e)return;e.textContent=msg||'';e.className=ok?'ok':'err'}
const org=()=>$('#orgSelect').value,site=()=>$('#siteSelect').value;
function orgObj(){return (bootstrap?.organizations||[]).find(o=>(o.id||o.cliente_id)===org())}
function sites(){const o=orgObj();if(!o)return[];return o.sites||o.sedes||[]}
function renderSiteSelect(){const arr=sites();$('#siteSelect').innerHTML=arr.map(s=>`<option value="${s.id}">${s.nombre||'Sede'}${s.codigo?` · ${s.codigo}`:''}</option>`).join('');renderUserSiteChecks();renderSitesList()}
function renderUserSiteChecks(){const arr=sites();$('#uSites').innerHTML=arr.map(s=>`<label class="check"><input type="checkbox" data-user-site value="${s.id}"><span>${s.nombre||'Sede'}</span></label>`).join('')||'<span class="muted">No hay sedes disponibles.</span>'}
function selectedUserSites(){return [...document.querySelectorAll('[data-user-site]:checked')].map(x=>x.value)}
function renderSitesList(){const arr=sites();$('#sitesList').innerHTML=arr.map(s=>`<div class="card"><div class="row"><div style="flex:1"><b>${s.nombre||'Sede'}</b><div class="muted">${s.codigo||'Sin código'} · ${s.direccion||'Sin dirección'} · ${s.telefono||'Sin teléfono'}</div></div><span class="pill">${s.activa===false?'Inactiva':'Activa'}</span></div></div>`).join('')||'<div class="muted">Sin sedes.</div>'}
function renderUsers(){const map=new Map(sites().map(s=>[s.id,s.nombre]));$('#mUsers').textContent=usersData.filter(x=>x.activo).length;$('#usersBody').innerHTML=usersData.map(x=>`<tr><td>${x.nombre||'—'}</td><td>${x.email||'—'}</td><td><span class="pill">${x.rol}</span></td><td>${(x.site_ids||[]).map(id=>map.get(id)||id).join(', ')||'Todas/ninguna según rol'}</td><td>${x.activo?'Activo':'Suspendido'}</td><td><button class="secondary" data-toggle="${x.user_id}" data-active="${x.activo?'0':'1'}">${x.activo?'Suspender':'Activar'}</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">Sin usuarios</td></tr>';document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async()=>{await edge('set_user',{organization_id:org(),user_id:b.dataset.toggle,active:b.dataset.active==='1'});await loadUsers()})}
function renderDashboard(){const entries=dashboard?.entries||[];$('#mPatio').textContent=entries.filter(x=>!x.salida_at&&x.estado==='en_patio').length;$('#mSalidas').textContent=entries.filter(x=>!!x.salida_at).length;$('#mMens').textContent=(dashboard?.monthly||[]).filter(x=>x.estado==='activa').length;$('#entriesBody').innerHTML=entries.slice(0,100).map(x=>`<tr><td>${x.recibo}</td><td>${x.placa}</td><td>${x.tipo_vehiculo}</td><td>${new Date(x.entrada_at).toLocaleString('es-CO')}</td><td>${x.salida_at?new Date(x.salida_at).toLocaleString('es-CO'):'En patio'}</td><td>${x.valor_total==null?'—':Number(x.valor_total).toLocaleString('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0})}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">Sin movimientos sincronizados</td></tr>';renderConfig();renderPayments()}
function renderConfig(){const c=dashboard?.config||{};$('#cNombre').value=c.nombre||'';$('#cNit').value=c.nit||'';$('#cDireccion').value=c.direccion||'';$('#cTelefono').value=c.telefono||'';$('#cPrefijo').value=c.prefijo||'PQ-';$('#cGracia').value=c.gracia_min??0;$('#cRedondeo').value=c.redondeo??50;const rs=dashboard?.rates||[];$('#ratesGrid').innerHTML=rs.map(r=>`<div class="card" data-rate="${r.tipo_vehiculo}"><b>${r.tipo_vehiculo}</b><label>Valor minuto</label><input data-r="valor_minuto" type="number" value="${r.valor_minuto||0}"><label>Tope día</label><input data-r="tope_dia" type="number" value="${r.tope_dia||0}"><label>Mensualidad</label><input data-r="mensualidad" type="number" value="${r.mensualidad||0}"></div>`).join('')}
function collectRates(){return [...document.querySelectorAll('[data-rate]')].map(card=>({tipo_vehiculo:card.dataset.rate,valor_minuto:Number(card.querySelector('[data-r="valor_minuto"]').value||0),tope_dia:Number(card.querySelector('[data-r="tope_dia"]').value||0),mensualidad:Number(card.querySelector('[data-r="mensualidad"]').value||0),activa:true}))}
function renderPayments(){const ms=dashboard?.payment_methods||[];$('#paymentsList').innerHTML=ms.map((m,i)=>`<div class="card" data-pay="${m.codigo}"><div class="row"><b style="flex:1">${m.nombre}</b><label class="check"><input data-p="activo" type="checkbox" ${m.activo?'checked':''}>Activo</label></div><div class="grid"><div><label>Dato / cuenta / llave</label><input data-p="dato" value="${m.dato||''}"></div><div><label>Enlace</label><input data-p="enlace" value="${m.enlace||''}"></div><div><label>Tipo de llave</label><input data-p="key_type" value="${m.key_type||''}"></div><div><label>Titular</label><input data-p="holder" value="${m.holder||''}"></div></div><input type="hidden" data-p="nombre" value="${m.nombre}"><input type="hidden" data-p="orden" value="${m.orden||(i+1)*10}"></div>`).join('')}
function collectPayments(){return [...document.querySelectorAll('[data-pay]')].map(card=>({codigo:card.dataset.pay,nombre:card.querySelector('[data-p="nombre"]').value,activo:card.querySelector('[data-p="activo"]').checked,dato:card.querySelector('[data-p="dato"]').value.trim(),enlace:card.querySelector('[data-p="enlace"]').value.trim(),key_type:card.querySelector('[data-p="key_type"]').value.trim(),holder:card.querySelector('[data-p="holder"]').value.trim(),orden:Number(card.querySelector('[data-p="orden"]').value||0)}))}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session){$('#loginCard').classList.remove('hidden');$('#app').classList.add('hidden');return}$('#loginCard').classList.add('hidden');$('#app').classList.remove('hidden');bootstrap=await edge('bootstrap');$('#sessionInfo').textContent=`${session.user.email} · ${bootstrap.platform_owner?'Propietario plataforma':'Usuario PARKSOLVEX'}`;const opts=(bootstrap.organizations||[]).map(o=>{const c=o.clientes||o;return `<option value="${o.id||o.cliente_id}">${c.nombre_negocio||'Cliente'}${o.rol?` · ${o.rol}`:''}</option>`}).join('');$('#orgSelect').innerHTML=opts;renderSiteSelect();await refresh()}
async function loadUsers(){if(!org())return;const u=await edge('list_users',{organization_id:org()});usersData=u.users||[];renderUsers()}
async function refresh(){if(!org()||!site())return;dashboard=await edge('dashboard',{organization_id:org(),site_id:site()});renderDashboard();await loadUsers()}
$('#loginBtn').onclick=async()=>{setMsg('#loginMsg','');const email=$('#email').value.trim(),password=$('#password').value;const {error}=await sb.auth.signInWithPassword({email,password});if(error)return setMsg('#loginMsg',error.message);setMsg('#loginMsg','Ingreso correcto',true);await boot()};
$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};$('#refreshBtn').onclick=refresh;$('#orgSelect').onchange=async()=>{renderSiteSelect();await refresh()};$('#siteSelect').onchange=refresh;
$('#inviteBtn').onclick=async()=>{setMsg('#inviteMsg','');try{const r=await edge('invite_user',{organization_id:org(),email:$('#uEmail').value.trim(),name:$('#uName').value.trim(),phone:$('#uPhone').value.trim(),role:$('#uRole').value,site_ids:selectedUserSites()});setMsg('#inviteMsg',r.invited?'Invitación enviada. El usuario debe abrir el correo y crear su contraseña.':'Usuario existente vinculado correctamente.',true);$('#uEmail').value='';$('#uName').value='';$('#uPhone').value='';await loadUsers()}catch(e){setMsg('#inviteMsg',e.message)}};
$('#createSiteBtn').onclick=async()=>{setMsg('#siteMsg','');try{await edge('create_site',{organization_id:org(),name:$('#sName').value.trim(),code:$('#sCode').value.trim(),address:$('#sAddress').value.trim(),phone:$('#sPhone').value.trim(),nit:$('#sNit').value.trim()});setMsg('#siteMsg','Sede creada correctamente.',true);bootstrap=await edge('bootstrap');renderSiteSelect();await refresh()}catch(e){setMsg('#siteMsg',e.message)}};
$('#saveConfigBtn').onclick=async()=>{setMsg('#configMsg','');try{await edge('save_site_configuration',{organization_id:org(),site_id:site(),config:{nombre:$('#cNombre').value.trim(),nit:$('#cNit').value.trim(),direccion:$('#cDireccion').value.trim(),telefono:$('#cTelefono').value.trim(),prefijo:$('#cPrefijo').value.trim(),gracia_min:Number($('#cGracia').value||0),redondeo:Number($('#cRedondeo').value||50)},rates:collectRates(),payment_methods:collectPayments()});setMsg('#configMsg','Configuración guardada.',true);await refresh()}catch(e){setMsg('#configMsg',e.message)}};
$('#savePaymentsBtn').onclick=$('#saveConfigBtn').onclick;
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.panel).classList.add('active')});
sb.auth.onAuthStateChange(()=>{});boot().catch(e=>setMsg('#loginMsg',e.message));