import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const SUPABASE_URL='https://epadzsrfsvckyjugcvpd.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_PxFa4vMqovqCIDOwEsoiBQ_2q2jETc_';
const sb=createClient(SUPABASE_URL,PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const $=s=>document.querySelector(s);let bootstrap=null;
async function edge(action,extra={}){const {data:{session}}=await sb.auth.getSession();if(!session)throw new Error('Sesión no disponible');const r=await fetch(`${SUPABASE_URL}/functions/v1/parkops-master`,{method:'POST',headers:{'content-type':'application/json','apikey':PUBLISHABLE_KEY,'authorization':`Bearer ${session.access_token}`},body:JSON.stringify({action,...extra})});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error||`HTTP ${r.status}`);return d}
function setMsg(id,msg,ok=false){const e=$(id);e.textContent=msg||'';e.className=ok?'ok':'err'}
function org(){return $('#orgSelect').value}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session){$('#loginCard').classList.remove('hidden');$('#app').classList.add('hidden');return}$('#loginCard').classList.add('hidden');$('#app').classList.remove('hidden');bootstrap=await edge('tenant_bootstrap');$('#sessionInfo').textContent=`${session.user.email} · PARKSOLVEX`;const opts=(bootstrap.memberships||[]).map(m=>{const c=Array.isArray(m.clientes)?m.clientes[0]:m.clientes;return `<option value="${m.cliente_id}">${c?.nombre_negocio||m.cliente_id} · ${m.rol}</option>`}).join('');if(!opts&&bootstrap.platform_owner){$('#orgSelect').innerHTML='<option value="">Propietario plataforma: seleccione cliente desde el generador de licencias</option>';return}$('#orgSelect').innerHTML=opts;await refresh()}
async function refresh(){if(!org())return;const [d,u]=await Promise.all([edge('tenant_dashboard',{organization_id:org()}),edge('tenant_list_users',{organization_id:org()})]);const entries=d.entries||[];$('#mPatio').textContent=entries.filter(x=>!x.salida_at&&x.estado==='en_patio').length;$('#mSalidas').textContent=entries.filter(x=>!!x.salida_at).length;$('#mMens').textContent=(d.monthly||[]).filter(x=>x.estado==='activa').length;$('#mUsers').textContent=(u.users||[]).filter(x=>x.activo).length;$('#usersBody').innerHTML=(u.users||[]).map(x=>`<tr><td>${x.nombre||'—'}</td><td>${x.email||'—'}</td><td><span class="pill">${x.rol}</span></td><td>${x.activo?'Activo':'Suspendido'}</td><td><button class="secondary" data-toggle="${x.user_id}" data-active="${x.activo?'0':'1'}">${x.activo?'Suspender':'Activar'}</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">Sin usuarios</td></tr>';document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async()=>{await edge('tenant_set_user',{organization_id:org(),user_id:b.dataset.toggle,active:b.dataset.active==='1'});await refresh()});$('#entriesBody').innerHTML=entries.slice(0,100).map(x=>`<tr><td>${x.recibo}</td><td>${x.placa}</td><td>${x.tipo_vehiculo}</td><td>${new Date(x.entrada_at).toLocaleString('es-CO')}</td><td>${x.salida_at?new Date(x.salida_at).toLocaleString('es-CO'):'En patio'}</td><td>${x.valor_total==null?'—':Number(x.valor_total).toLocaleString('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0})}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">Sin movimientos sincronizados</td></tr>'}
$('#loginBtn').onclick=async()=>{setMsg('#loginMsg','');const email=$('#email').value.trim(),password=$('#password').value;const {error}=await sb.auth.signInWithPassword({email,password});if(error){setMsg('#loginMsg',error.message);return}setMsg('#loginMsg','Ingreso correcto',true);await boot()};
$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};$('#refreshBtn').onclick=refresh;$('#orgSelect').onchange=refresh;
$('#inviteBtn').onclick=async()=>{setMsg('#inviteMsg','');try{await edge('tenant_invite_user',{organization_id:org(),email:$('#uEmail').value.trim(),name:$('#uName').value.trim(),phone:$('#uPhone').value.trim(),role:$('#uRole').value});setMsg('#inviteMsg','Invitación enviada y usuario registrado.',true);$('#uEmail').value='';$('#uName').value='';$('#uPhone').value='';await refresh()}catch(e){setMsg('#inviteMsg',e.message)}};
boot().catch(e=>setMsg('#loginMsg',e.message));
