-- PARKOPS: recibos 100% digitales, tarifas configurables y recarga electrica
create table if not exists public.parkops_configuracion (
 id bigint generated by default as identity primary key,
 sede_id uuid,
 nombre_parqueadero text not null default 'PARKOPS',
 moneda text not null default 'COP',
 medios_pago text[] not null default array['EFECTIVO','TARJETA','PSE','TRANSFERENCIA','NEQUI','DAVIPLATA'],
 solo_recibo_digital boolean not null default true,
 whatsapp_recibo boolean not null default true,
 requiere_nombre_recibe boolean not null default true,
 updated_at timestamptz not null default now(),
 unique(sede_id)
);
create table if not exists public.parkops_tarifas (
 id bigint generated by default as identity primary key,sede_id uuid,perfil text not null,
 tipo_vehiculo text not null check (tipo_vehiculo in ('AUTO','MOTO','BICICLETA','PATINETA')),
 valor numeric(12,2) not null default 0,cobra_parqueo boolean not null default true,activo boolean not null default true,
 updated_at timestamptz not null default now(),unique(sede_id,perfil,tipo_vehiculo)
);
create table if not exists public.parkops_recarga_tarifas (
 id bigint generated by default as identity primary key,sede_id uuid,minutos integer not null check(minutos>0),
 valor numeric(12,2) not null default 0,activo boolean not null default true,updated_at timestamptz not null default now()
);
create table if not exists public.parkops_recibos_digitales (
 id bigint generated by default as identity primary key,sede_id uuid,numero text not null,placa text,tipo_vehiculo text,perfil text,
 whatsapp text,recibido_por text,fecha_ingreso timestamptz,fecha_salida timestamptz default now(),medio_pago text,
 valor_parqueadero numeric(12,2) default 0,minutos_recarga integer default 0,valor_recarga numeric(12,2) default 0,
 total numeric(12,2) default 0,estado_envio text default 'PENDIENTE',enviado_at timestamptz,created_at timestamptz default now()
);
alter table if exists public.sesiones add column if not exists whatsapp text;
alter table if exists public.sesiones add column if not exists tipo_vehiculo text default 'AUTO';
alter table if exists public.sesiones add column if not exists perfil text default 'INVITADO';
alter table if exists public.sesiones add column if not exists cortesia boolean default false;
alter table if exists public.sesiones add column if not exists recibido_por text;
alter table if exists public.sesiones add column if not exists medio_pago text;
alter table if exists public.sesiones add column if not exists recibo_digital text;
alter table if exists public.recargas add column if not exists minutos integer;
alter table if exists public.recargas add column if not exists tarifa numeric(12,2) default 0;
insert into public.parkops_tarifas(perfil,tipo_vehiculo,valor,cobra_parqueo) values
 ('SOCIO','AUTO',0,false),('SOCIO','MOTO',0,false),('SOCIO','BICICLETA',0,false),('SOCIO','PATINETA',0,false),
 ('INVITADO','AUTO',35000,true),('INVITADO','MOTO',21000,true),('INVITADO','BICICLETA',0,false),('INVITADO','PATINETA',0,false),
 ('CORTESIA','AUTO',0,false),('CORTESIA','MOTO',0,false),('CORTESIA','BICICLETA',0,false),('CORTESIA','PATINETA',0,false),
 ('GENERAL','MOTO',9200,true),('GENERAL','BICICLETA',0,false),('GENERAL','PATINETA',0,false)
on conflict do nothing;
alter table public.parkops_configuracion enable row level security;
alter table public.parkops_tarifas enable row level security;
alter table public.parkops_recarga_tarifas enable row level security;
alter table public.parkops_recibos_digitales enable row level security;
