-- PARKOPS: mejoras tarifas, WhatsApp, recibo digital y recarga electrica
create table if not exists public.parkops_tarifas (
  id bigint generated by default as identity primary key,
  sede_id uuid,
  perfil text not null,
  tipo_vehiculo text not null check (tipo_vehiculo in ('AUTO','MOTO','BICICLETA','PATINETA')),
  valor numeric(12,2) not null default 0,
  cobra_parqueo boolean not null default true,
  activo boolean not null default true,
  updated_at timestamptz not null default now(),
  unique(sede_id, perfil, tipo_vehiculo)
);

create table if not exists public.parkops_recarga_tarifas (
  id bigint generated by default as identity primary key,
  sede_id uuid,
  minutos integer not null check (minutos > 0),
  valor numeric(12,2) not null default 0,
  activo boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table if exists public.sesiones add column if not exists whatsapp text;
alter table if exists public.sesiones add column if not exists tipo_vehiculo text default 'AUTO';
alter table if exists public.sesiones add column if not exists perfil text default 'INVITADO';
alter table if exists public.sesiones add column if not exists cortesia boolean default false;
alter table if exists public.sesiones add column if not exists recibo_digital text;
alter table if exists public.recargas add column if not exists minutos integer;
alter table if exists public.recargas add column if not exists tarifa numeric(12,2) default 0;

-- Valores iniciales solicitados. Todo queda editable desde Admin.
insert into public.parkops_tarifas (perfil,tipo_vehiculo,valor,cobra_parqueo) values
 ('SOCIO','AUTO',0,false),('SOCIO','MOTO',0,false),('SOCIO','BICICLETA',0,false),('SOCIO','PATINETA',0,false),
 ('INVITADO','AUTO',35000,true),('INVITADO','MOTO',21000,true),('INVITADO','BICICLETA',0,false),('INVITADO','PATINETA',0,false),
 ('CORTESIA','AUTO',0,false),('CORTESIA','MOTO',0,false),('CORTESIA','BICICLETA',0,false),('CORTESIA','PATINETA',0,false),
 ('GENERAL','MOTO',9200,true),('GENERAL','BICICLETA',0,false),('GENERAL','PATINETA',0,false)
on conflict do nothing;

alter table public.parkops_tarifas enable row level security;
alter table public.parkops_recarga_tarifas enable row level security;
