import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cfg=window.PARKOPS_CONFIG||{}, mode=document.body.dataset.console;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const supabase=(cfg.supabaseUrl&&cfg.supabaseAnonKey&&!cfg.supabaseUrl.includes('__'))?createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true}}):null;
let org=null;
const fmt=n=>new Intl.NumberFormat('es-CO').format(n||0), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function note(msg,err=false){$$('.notice').forEach(n=>{n.textContent=msg;n.classList.remove('hidden');n.style.color=err?'#ffb8bf':''});setTimeout(()=>$$('.notice').forEach(n=>n.classList.add('hidden')),5000)}
function app(on){$('#login').classList.toggle('hidden',on);$('#app').classList.toggle('hidden',!on)}
async function api(action,payload={}){const {data:{session}}=await supabase.auth.getSession();const r=await fetch(`${cfg.supabaseUrl}/functions/v1/parkops-master`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${session.access_token}`},body:JSON.stringify({action,...payload})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Error del servicio');return j}
async function login(e){e.preventDefault();if(!supabase)return note('Configure SUPABASE_URL y SUPABASE_ANON_KEY en GitHub antes de publicar.',true);const {error}=await supabase.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)return note(error.message,true);boot()}
async function boot(){if(!supabase)return app(false);const {data:{session}}=await supabase.auth.getSession();if(!session)return app(false);if(mode==='owner'){try{const me=await api('owner_bootstrap');$('#who').textContent=me.email||session.user.email;app(true);await loadOwner()}catch(e){await supabase.auth.signOut();app(false);note('Cuenta sin permiso de propietario maestro.',true)}}else{const {data:m,error}=await supabase.from('memberships').select('id,organization_id,role,active,organizations(id,legal_name,trade_name,status)').eq('user_id',session.user.id).eq('active',true).limit(1).maybeSingle();if(error||!m){await supabase.auth.signOut();app(false);return note('Usuario sin organización activa.',true)}org=m.organizations;$('#who').textContent=`${session.user.email} · ${m.role}`;$('#orgName').textContent=org.trade_name||org.legal_name;app(true);await loadAdmin()}}
async function logout(){await supabase.auth.signOut();location.reload()}
function nav(){$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.section').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active')})}
function rows(el,items,cols){el.innerHTML=items.length?items.map(x=>`<tr>${cols.map(c=>`<td>${c(x)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${cols.length}" class="muted">Sin registros</td></tr>`}
async function loadAdmin(){nav();const oid=org.id;const [users,sites,tickets,subs,inst]=await Promise.all([supabase.from('memberships').select('id,role,active,profiles:user_id(full_name),user_id').eq('organization_id',oid),supabase.from('sites').select('*').eq('organization_id',oid).order('name'),supabase.from('parking_tickets').select('id,status,total,entry_at').eq('organization_id',oid),supabase.from('subscriptions').select('*,plans(name)').eq('organization_id',oid).order('starts_at',{ascending:false}).limit(1),supabase.from('app_installations').select('*').eq('organization_id',oid).order('created_at',{ascending:false})]);
const u=users.data||[],s=sites.data||[],t=tickets.data||[],i=inst.data||[];$('#kUsers').textContent=fmt(u.filter(x=>x.active).length);$('#kSites').textContent=fmt(s.filter(x=>x.active).length);$('#kOpen').textContent=fmt(t.filter(x=>x.status==='open').length);$('#kRevenue').textContent='$ '+fmt(t.reduce((a,x)=>a+Number(x.total||0),0));$('#plan').textContent=subs.data?.[0]?.plans?.name||'Sin plan';rows($('#usersBody'),u,[x=>esc(x.profiles?.full_name||'Usuario'),x=>esc(x.role),x=>x.active?'<span class="status">Activo</span>':'<span class="status off">Inactivo</span>']);rows($('#sitesBody'),s,[x=>esc(x.name),x=>esc(x.city),x=>fmt(x.capacity),x=>x.active?'<span class="status">Activa</span>':'<span class="status off">Inactiva</span>']);rows($('#devicesBody'),i,[x=>esc(x.device_id),x=>esc(x.label||'Android'),x=>esc(x.app_version||'—'),x=>x.active?'<span class="status">Activo</span>':'<span class="status off">Bloqueado</span>']);
$('#inviteBtn').onclick=()=>$('#userModal').classList.add('open');$('#siteBtn').onclick=()=>$('#siteModal').classList.add('open');$('#userForm').onsubmit=async e=>{e.preventDefault();try{await api('invite_user',{organization_id:oid,email:$('#uEmail').value,full_name:$('#uName').value,role:$('#uRole').value});$('#userModal').classList.remove('open');note('Invitación creada correctamente.');await loadAdmin()}catch(err){note(err.message,true)}};$('#siteForm').onsubmit=async e=>{e.preventDefault();const {error}=await supabase.from('sites').insert({organization_id:oid,name:$('#sName').value,city:$('#sCity').value,address:$('#sAddress').value,capacity:Number($('#sCapacity').value||0)});if(error)return note(error.message,true);$('#siteModal').classList.remove('open');note('Sede creada.');await loadAdmin()}}
async function loadOwner(){nav();const d=await api('owner_dashboard');$('#kClients').textContent=fmt(d.metrics.clients);$('#kLicenses').textContent=fmt(d.metrics.active_licenses);$('#kDevices').textContent=fmt(d.metrics.active_devices);$('#kMRR').textContent='$ '+fmt(d.metrics.mrr_cop);rows($('#clientsBody'),d.organizations,[x=>esc(x.trade_name),x=>esc(x.tax_id||'—'),x=>esc(x.plan_name||'—'),x=>x.status==='active'?'<span class="status">Activo</span>':`<span class="status off">${esc(x.status)}</span>`]);rows($('#licensesBody'),d.licenses,[x=>esc(x.license_id),x=>esc(x.trade_name),x=>esc(x.device_id),x=>esc(x.plan_code),x=>x.revoked_at?'<span class="status off">Revocada</span>':'<span class="status">Activa</span>']);
$('#clientBtn').onclick=()=>$('#clientModal').classList.add('open');$('#licenseBtn').onclick=()=>{$('#licenseModal').classList.add('open');$('#lOrg').innerHTML=d.organizations.map(x=>`<option value="${esc(x.id)}">${esc(x.trade_name)}</option>`).join('')};$('#clientForm').onsubmit=async e=>{e.preventDefault();try{await api('create_organization',{legal_name:$('#cLegal').value,trade_name:$('#cTrade').value,tax_id:$('#cNit').value,email:$('#cEmail').value,plan_code:$('#cPlan').value,admin_name:$('#cAdminName').value,admin_email:$('#cAdminEmail').value});$('#clientModal').classList.remove('open');note('Cliente creado e invitación enviada.');await loadOwner()}catch(err){note(err.message,true)}};$('#licenseForm').onsubmit=async e=>{e.preventDefault();try{const x=await api('issue_license',{organization_id:$('#lOrg').value,device_id:$('#lDevice').value.trim(),plan_code:$('#lPlan').value,days:$('#lDays').value?Number($('#lDays').value):null,label:$('#lLabel').value});$('#licenseOut').textContent=x.license_key;$('#licenseOut').classList.remove('hidden');note('Licencia firmada y registrada.');await loadOwner()}catch(err){note(err.message,true)}}}
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));$('#loginForm').onsubmit=login;$('#logout').onclick=logout;boot();