(()=>{
'use strict';
const V='1.6.0',TYPES=['carro','moto','bicicleta','patineta'];
const LABEL={carro:'Carros',moto:'Motos',bicicleta:'Bicicletas',patineta:'Patinetas'};
const PREFIX={carro:'C',moto:'M',bicicleta:'B',patineta:'P'};
function initCfg(){cfg.capacity=Object.assign({enabled:false,carro:0,moto:0,bicicleta:0,patineta:0},cfg.capacity||{});cfg.billing=Object.assign({enabled:false,provider:'',url:'',buttonText:'FACTURA ELECTRÓNICA',mode:'external_url'},cfg.billing||{});let changed=false;ingresos.forEach(r=>{if(r.status==null){r.status=r.salida?'SALIDO':'EN_PATIO';changed=true}if(r.occupiesSlot==null){r.occupiesSlot=!r.salida;changed=true}if(r.slotProvisional==null){r.slotProvisional=false;changed=true}});TYPES.forEach(t=>{const used=new Set(ingresos.filter(r=>r.tipo===t&&r.occupiesSlot&&r.slotNumber).map(r=>+r.slotNumber));ingresos.filter(r=>r.tipo===t&&r.occupiesSlot&&!r.slotNumber).forEach(r=>{let n=1;while(used.has(n))n++;used.add(n);r.slotNumber=n;r.slotCode=`${PREFIX[t]}-${String(n).padStart(3,'0')}`;changed=true})});sCfg();if(changed)sIng()}
function occupied(t){return ingresos.filter(r=>r.tipo===t&&r.occupiesSlot!==false&&!r.salida).length}
function nextSlot(t){const used=new Set(ingresos.filter(r=>r.tipo===t&&r.occupiesSlot!==false&&!r.salida).map(r=>+r.slotNumber).filter(Boolean));const max=cfg.capacity.enabled?Math.max(0,+cfg.capacity[t]||0):999999;for(let n=1;n<=max;n++)if(!used.has(n))return n;return null}
function slotCode(t,n){return n?`${PREFIX[t]||'X'}-${String(n).padStart(3,'0')}`:''}
function availability(t){const cap=Math.max(0,+cfg.capacity[t]||0),occ=occupied(t);return{cap,occ,free:Math.max(0,cap-occ),pct:cap?Math.min(100,occ/cap*100):0}}
function capacityOk(t){if(!cfg.capacity.enabled)return true;const a=availability(t);return a.cap>0&&a.free>0}
const oldDatosRecibo=datosRecibo;datosRecibo=function(reg,liq){const d=oldDatosRecibo(reg,liq);d.cupo=reg.slotCode||'—';d.vehiculo=`${d.vehiculo} · Cupo ${d.cupo}`;return d};
const oldRegistrarEntrada=registrarEntrada;registrarEntrada=function(enviar){const placa=norm(inPlaca.value);if(placa.length<3)return oldRegistrarEntrada(enviar);if(ingresos.some(i=>i.placa===placa&&!i.salida)){avisar(`${placa} ya está en el patio`,'err');return}if(!capacityOk(tipoSel)){const a=availability(tipoSel);avisar(a.cap?`SIN CUPOS DISPONIBLES PARA ${LABEL[tipoSel].toUpperCase()}`:`Capacidad de ${LABEL[tipoSel]} configurada en 0`,'err');return}const n=nextSlot(tipoSel);const before=new Set(ingresos.map(x=>x.id));oldRegistrarEntrada(enviar);const reg=ingresos.find(x=>!before.has(x.id));if(!reg)return;reg.slotNumber=n||1;reg.slotCode=slotCode(reg.tipo,reg.slotNumber);reg.occupiesSlot=true;reg.slotProvisional=!window.ParkopsContingency?.isOnline?.();reg.status='EN_PATIO';sIng();refrescar()};
const oldTarjetaAuto=tarjetaAuto;tarjetaAuto=function(i){const raw=oldTarjetaAuto(i);const badge=`<span class="chip" style="margin-left:5px">${i.slotCode||'Sin cupo'}</span>${i.status==='LIQUIDADO'?'<span class="chip" style="margin-left:5px;background:#f59e0b;color:#111">LIQUIDADO</span>':''}`;return raw.replace('</div></div>',`${badge}</div></div>`)};
function capacityPanel(){const rows=TYPES.map(t=>{const a=availability(t);return `<div style="padding:10px;border:1px solid var(--linea);border-radius:10px"><b>${LABEL[t]}</b><div class="nota">${a.occ} / ${a.cap||'—'} ocupados · <b>${cfg.capacity.enabled?a.free:'∞'} disponibles</b>${a.cap?` · ${a.pct.toFixed(1)}%`:''}</div></div>`}).join('');const cap=TYPES.reduce((s,t)=>s+(+cfg.capacity[t]||0),0),occ=TYPES.reduce((s,t)=>s+occupied(t),0);return `<div id="parkops-capacity-panel" class="tarjeta" style="margin-bottom:12px"><h2>Disponibilidad en tiempo real</h2><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px">${rows}</div><p class="nota" style="margin:10px 0 0"><b>Total:</b> ${occ} ocupados · ${cfg.capacity.enabled?Math.max(0,cap-occ)+' disponibles':'control de capacidad no activado'}</p></div>`}
const oldPintarPatio=pintarPatio;pintarPatio=function(){document.getElementById('parkops-capacity-panel')?.remove();oldPintarPatio();const p=document.getElementById('patio');if(p)p.insertAdjacentHTML('beforebegin',capacityPanel())};
function freeze(reg,liq,medio){const now=Date.now();reg.liquidatedAt=reg.liquidatedAt||now;reg.billingFrozenAt=reg.billingFrozenAt||now;reg.durationMinutesFrozen=reg.durationMinutesFrozen??liq.min;reg.valor=reg.valor??liq.total;reg.valorParqueo=reg.valorParqueo??liq.parqueo;reg.valorRecarga=reg.valorRecarga??liq.recarga;reg.medio=reg.medio||medio;reg.status='LIQUIDADO';reg.occupiesSlot=true;sIng();return reg}
function frozenLiq(reg){return{total:+reg.valor||0,parqueo:+reg.valorParqueo||0,recarga:+reg.valorRecarga||0,min:+reg.durationMinutesFrozen||0,lineas:[`Liquidación congelada ${fechaHora(reg.billingFrozenAt||reg.liquidatedAt)}`],mens:false}}
function validBillingUrl(u){try{const x=new URL(u);return x.protocol==='https:'||x.protocol==='http:'}catch{return false}}
function addBillingButton(card){if(!cfg.billing?.enabled||!validBillingUrl(cfg.billing.url)||document.getElementById('btnFacturaElectronica'))return;const b=document.createElement('button');b.className='btn sec';b.id='btnFacturaElectronica';b.textContent=cfg.billing.buttonText||'FACTURA ELECTRÓNICA';b.onclick=()=>{location.href=cfg.billing.url};card.appendChild(b)}
const oldMostrarLiquidacion=mostrarLiquidacion;mostrarLiquidacion=function(id,simMin){const reg=ingresos.find(i=>i.id===id);if(!reg)return;oldMostrarLiquidacion(id,reg.status==='LIQUIDADO'?(reg.durationMinutesFrozen||1):simMin);const panel=document.getElementById('panelLiq');if(!panel)return;if(reg.status==='LIQUIDADO'){const liq=frozenLiq(reg),tot=panel.querySelector('.tot');if(tot)tot.textContent=pesos(liq.total);const det=panel.querySelector('.det');if(det)det.innerHTML=`· <b>LIQUIDADO</b> · valor y tiempo congelados<br>· Permanencia facturada: ${dur(liq.min*60000)}<br>· Cupo ${reg.slotCode||'—'} continúa ocupado`;panel.querySelectorAll('.simul,#btnActualizar,#btnEnviarPago,#btnConfirmar').forEach(x=>x.style.display='none');const card=panel.querySelector('.tarjeta');if(card&&!document.getElementById('btnLiberarCupo')){const b=document.createElement('button');b.className='btn';b.id='btnLiberarCupo';b.textContent='MARCAR SALIDA · LIBERAR CUPO';b.onclick=()=>{if(!confirm(`¿Confirmar salida física de ${reg.placa} y liberar ${reg.slotCode||'el cupo'}?`))return;reg.salida=Date.now();reg.exitAt=reg.salida;reg.occupiesSlot=false;reg.status='SALIDO';sIng();avisar(`Salida física ${reg.placa} · cupo ${reg.slotCode||''} liberado`,'ok');document.getElementById('busca').value='';document.getElementById('resultados').innerHTML='';panel.innerHTML='';refrescar()};card.appendChild(b);addBillingButton(card)}return}const send=panel.querySelector('#btnEnviarPago'),confirmBtn=panel.querySelector('#btnConfirmar');if(send){const clone=send.cloneNode(true);send.replaceWith(clone);clone.addEventListener('click',()=>{const fin=Date.now(),liq=liquidar(reg.entrada,fin,reg.tipo,reg.placa,reg.electrico,reg.kwh||0);freeze(reg,liq,document.getElementById('medioPago')?.value);const r=Object.assign({},reg,{salida:reg.liquidatedAt});abrirWA(reg.celular,armar(cfg.pPago,datosRecibo(r,liq)),`Recibo de pago ${reg.recibo}`,liq.total);avisar(`Liquidación congelada · ${reg.placa}`,'ok');setTimeout(()=>mostrarLiquidacion(reg.id),150)})}if(confirmBtn){confirmBtn.textContent='LIQUIDAR PAGO · NO LIBERA CUPO';const clone=confirmBtn.cloneNode(true);confirmBtn.replaceWith(clone);clone.addEventListener('click',()=>{const fin=Date.now(),liq=liquidar(reg.entrada,fin,reg.tipo,reg.placa,reg.electrico,reg.kwh||0);freeze(reg,liq,document.getElementById('medioPago')?.value);avisar(`Pago liquidado · ${reg.slotCode||''} sigue ocupado`,'ok');mostrarLiquidacion(reg.id)})}};
function injectSettings(){if(document.getElementById('parkops-capacity-settings'))return;const view=document.getElementById('v-ajustes');if(!view)return;const d=document.createElement('details');d.className='acordeon';d.id='parkops-capacity-settings';d.innerHTML=`<summary>Capacidad y facturación electrónica</summary><div class="cuerpo"><h3>Capacidad del parqueadero</h3><label class="switch"><input id="capEnabled" type="checkbox" ${cfg.capacity.enabled?'checked':''}><span class="txt">Activar control máximo de cupos</span></label><div class="fila">${TYPES.map(t=>`<div class="campo"><label>${LABEL[t]}</label><input type="number" min="0" data-cap="${t}" value="${+cfg.capacity[t]||0}"></div>`).join('')}</div><button class="btn" id="btnCapSave">Guardar capacidad</button><hr style="border:0;border-top:1px solid var(--linea);margin:18px 0"><h3>Facturación electrónica</h3><label class="switch"><input id="billEnabled" type="checkbox" ${cfg.billing.enabled?'checked':''}><span class="txt">Habilitar botón de factura electrónica</span></label><div class="campo"><label>Proveedor</label><input id="billProvider" value="${esc(cfg.billing.provider||'')}"></div><div class="campo"><label>URL del facturador</label><input id="billUrl" type="url" value="${esc(cfg.billing.url||'')}" placeholder="https://..."></div><div class="campo"><label>Texto del botón</label><input id="billText" value="${esc(cfg.billing.buttonText||'FACTURA ELECTRÓNICA')}"></div><button class="btn" id="btnBillSave">Guardar facturación</button></div>`;view.appendChild(d);d.querySelector('#btnCapSave').onclick=()=>{cfg.capacity.enabled=d.querySelector('#capEnabled').checked;d.querySelectorAll('[data-cap]').forEach(i=>cfg.capacity[i.dataset.cap]=Math.max(0,+i.value||0));sCfg();avisar('Capacidad guardada','ok');refrescar()};d.querySelector('#btnBillSave').onclick=()=>{const u=d.querySelector('#billUrl').value.trim(),en=d.querySelector('#billEnabled').checked;if(en&&!validBillingUrl(u)){avisar('URL de facturación inválida. Usa https://','err');return}cfg.billing={enabled:en,provider:d.querySelector('#billProvider').value.trim(),url:u,buttonText:d.querySelector('#billText').value.trim()||'FACTURA ELECTRÓNICA',mode:'external_url'};sCfg();avisar('Facturación electrónica guardada','ok')}}
initCfg();injectSettings();const mo=new MutationObserver(()=>injectSettings());mo.observe(document.documentElement,{childList:true,subtree:true});window.ParkopsCapacity={version:V,availability,nextSlot,validBillingUrl};if(window.ParkopsContingency)window.ParkopsContingency.version=V;
})();