(()=>{'use strict';
const KEY='parkops.admin.auth.v1',ITER=210000;let unlocked=false,lastVisible=false;
const enc=s=>new TextEncoder().encode(s),b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))),unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function derive(p,s){const k=await crypto.subtle.importKey('raw',enc(p),'PBKDF2',false,['deriveBits']);return b64(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:s,iterations:ITER},k,256))}
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
async function setPassword(p){const salt=crypto.getRandomValues(new Uint8Array(16)),hash=await derive(p,salt);localStorage.setItem(KEY,JSON.stringify({v:1,alg:'PBKDF2-SHA256',iterations:ITER,salt:b64(salt),hash,createdAt:Date.now()}))}
async function verify(p){const a=read();if(!a)return false;return (await derive(p,unb64(a.salt)))===a.hash}
function toast(m,t='ok'){if(typeof avisar==='function')avisar(m,t)}
function modal(first=false){if(document.getElementById('adminAuth167'))return;const d=document.createElement('div');d.id='adminAuth167';d.style.cssText='position:fixed;inset:0;z-index:2147483647;background:rgba(0,0,0,.86);display:flex;align-items:center;justify-content:center;padding:18px';d.innerHTML=`<div style="width:min(430px,100%);background:var(--tarjeta,#171b20);color:inherit;border:1px solid var(--linea,#555);border-radius:16px;padding:20px;box-shadow:0 18px 60px #000"><h2 style="margin-top:0">${first?'CREAR CONTRASEÑA ADMINISTRATIVA':'CONFIGURACIÓN PROTEGIDA'}</h2><p class="nota">${first?'Primer acceso a Configuración: crea la contraseña del propietario. Desde ese momento será necesaria para volver a entrar y modificar tarifas o parámetros.':'Ingresa la contraseña del propietario para acceder a Configuración.'}</p><div class="campo"><label>Contraseña</label><input id="adminPass167" type="password" autocomplete="current-password" minlength="6"></div>${first?'<div class="campo"><label>Confirmar contraseña</label><input id="adminPass2167" type="password" autocomplete="new-password" minlength="6"></div>':''}<div id="adminErr167" style="min-height:22px;color:#ff7676;margin:7px 0"></div><div style="display:flex;gap:8px"><button class="btn" id="adminOk167">${first?'CREAR Y PROTEGER':'DESBLOQUEAR'}</button>${first?'':'<button class="btn sec" id="adminCancel167">CANCELAR</button>'}</div></div>`;document.body.appendChild(d);const p=d.querySelector('#adminPass167'),err=d.querySelector('#adminErr167');p.focus();async function go(){const v=p.value;if(first){const v2=d.querySelector('#adminPass2167').value;if(v.length<6){err.textContent='Usa mínimo 6 caracteres.';return}if(v!==v2){err.textContent='Las contraseñas no coinciden.';return}await setPassword(v);unlocked=true;d.remove();apply();toast('Contraseña administrativa creada. Configuración protegida.','ok')}else{if(await verify(v)){unlocked=true;d.remove();apply();toast('Configuración desbloqueada','ok')}else{err.textContent='Contraseña incorrecta.';p.value='';p.focus()}}}d.querySelector('#adminOk167').onclick=go;p.onkeydown=e=>{if(e.key==='Enter')go()};d.querySelector('#adminCancel167')?.addEventListener('click',()=>d.remove())}
function gate(){const v=document.getElementById('v-ajustes');if(!v)return;let g=document.getElementById('adminGate167');if(!g){g=document.createElement('div');g.id='adminGate167';g.style.cssText='padding:24px;text-align:center;border:1px solid var(--linea);border-radius:14px;margin:14px 0';g.innerHTML='<h2>🔒 CONFIGURACIÓN PROTEGIDA</h2><p class="nota">Solo el propietario o administrador autorizado puede modificar tarifas y parámetros.</p><button class="btn" id="unlockAdmin167">DESBLOQUEAR CONFIGURACIÓN</button>';v.prepend(g);g.querySelector('#unlockAdmin167').onclick=()=>modal(!read())}[...v.children].forEach(x=>{if(x!==g)x.style.display=unlocked?'':'none'});g.style.display=unlocked?'none':''}
function apply(){gate()}
function tick(){const v=document.getElementById('v-ajustes');if(!v)return;const vis=getComputedStyle(v).display!=='none'&&getComputedStyle(v).visibility!=='hidden';if(lastVisible&&!vis){unlocked=false;apply()}if(vis&&!lastVisible)apply();lastVisible=vis}
function init(){apply();setInterval(tick,400);document.addEventListener('click',e=>{const v=document.getElementById('v-ajustes');if(!unlocked&&v?.contains(e.target)&&!e.target.closest('#adminGate167,#adminAuth167')){e.preventDefault();e.stopImmediatePropagation();modal(!read())}},true);window.Parkops167={version:'1.6.7',locked:()=>!unlocked,lock:()=>{unlocked=false;apply()}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();