(()=>{'use strict';
const V='1.6.5',DEF={helmetFee:0,bathroomFee:0,vatPercent:0};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function money(n){return typeof pesos==='function'?pesos(+n||0):'$'+Math.round(+n||0).toLocaleString('es-CO')}
function ensure(){if(typeof cfg==='undefined')return false;cfg.services=Object.assign({},DEF,cfg.services||{});return true}
function save(){if(typeof sCfg==='function')sCfg()}
function mountSettings(){if(!ensure())return;const view=$('#v-ajustes');if(!view||$('#servicesSettings165'))return;const d=document.createElement('details');d.id='servicesSettings165';d.className='acordeon';d.innerHTML=`<summary>Servicios adicionales e IVA</summary><div class="cuerpo"><p class="nota">Estos valores se administran aquí. En Registrar ingreso el operario solo verá los checks para activar cada servicio.</p><div class="fila"><div class="campo"><label>Guarda casco (COP)</label><input id="helmetFee165" type="number" min="0" step="100" inputmode="numeric" value="${+cfg.services.helmetFee||0}"></div><div class="campo"><label>Uso de baño (COP)</label><input id="bathroomFee165" type="number" min="0" step="100" inputmode="numeric" value="${+cfg.services.bathroomFee||0}"></div></div><div class="campo"><label>IVA (%)</label><input id="vatPercent165" type="number" min="0" max="100" step="0.01" inputmode="decimal" value="${+cfg.services.vatPercent||0}"><div class="nota">Deje 0 si no aplica. Para IVA del 19%, configure 19.</div></div><button class="btn" id="saveServices165">GUARDAR SERVICIOS E IVA</button></div>`;view.appendChild(d);$('#saveServices165').onclick=()=>{cfg.services.helmetFee=Math.max(0,+$('#helmetFee165').value||0);cfg.services.bathroomFee=Math.max(0,+$('#bathroomFee165').value||0);cfg.services.vatPercent=Math.min(100,Math.max(0,+$('#vatPercent165').value||0));save();if(typeof avisar==='function')avisar('Servicios e IVA guardados','ok')}}
function mountEntry(){const anchor=$('#entryExtra164')||$('#tipos');if(!anchor||$('#entryServices165'))return;const box=document.createElement('div');box.id='entryServices165';box.style.cssText='margin:12px 0;padding:12px;border:1px solid var(--linea);border-radius:12px';box.innerHTML=`<b>SERVICIOS ADICIONALES</b><div style="display:grid;gap:8px;margin-top:10px"><label class="switch"><input id="helmet165" type="checkbox"><span class="txt">Guarda / deja casco</span></label><label class="switch"><input id="bathroom165" type="checkbox"><span class="txt">Uso de baño</span></label></div>`;anchor.insertAdjacentElement('afterend',box);const obs=$('#obs');if(obs){const lab=obs.closest('.campo')?.querySelector('label');if(lab)lab.textContent='Observaciones';obs.placeholder='Ej. deja llaves, recoge familia, novedad del vehículo…'}}
const baseRegister=registrarEntrada;registrarEntrada=function(enviar){mountEntry();const helmet=!!$('#helmet165')?.checked,bathroom=!!$('#bathroom165')?.checked,obs=$('#obs')?.value.trim()||'';const before=new Set(ingresos.map(x=>x.id));baseRegister(enviar);const reg=ingresos.find(x=>!before.has(x.id));if(!reg)return;ensure();reg.helmetSelected=helmet;reg.bathroomSelected=bathroom;reg.helmetFee=helmet?(+cfg.services.helmetFee||0):0;reg.bathroomFee=bathroom?(+cfg.services.bathroomFee||0):0;reg.vatPercent=+cfg.services.vatPercent||0;reg.obs=obs;reg.servicesSnapshot=true;if(typeof sIng==='function')sIng();setTimeout(()=>{mountEntry()},0)};
const baseLiquidar=liquidar;liquidar=function(entrada,fin,tipo,placa,electrico,kwh){const out=baseLiquidar(entrada,fin,tipo,placa,electrico,kwh),reg=ingresos.find(x=>x.placa===placa&&!x.salida);if(!reg||reg.isCourtesy)return out;const casco=reg.helmetSelected?Math.max(0,+reg.helmetFee||0):0,bano=reg.bathroomSelected?Math.max(0,+reg.bathroomFee||0):0,pct=Math.max(0,+reg.vatPercent||0);const base=+out.total||0,subtotal=base+casco+bano,iva=Math.round(subtotal*pct/100),total=subtotal+iva;out.casco=casco;out.bano=bano;out.subtotal=subtotal;out.iva=iva;out.ivaPorcentaje=pct;out.total=total;out.lineas=[...(out.lineas||[])];if(casco)out.lineas.push(`Guarda casco: ${money(casco)}`);if(bano)out.lineas.push(`Uso de baño: ${money(bano)}`);if(pct){out.lineas.push(`Subtotal: ${money(subtotal)}`);out.lineas.push(`IVA ${pct}%: ${money(iva)}`)}return out};
const baseDatos=datosRecibo;datosRecibo=function(reg,liq){const d=baseDatos(reg,liq);const extra=[];if(reg.obs)extra.push(`Observaciones: ${reg.obs}`);if(reg.helmetSelected)extra.push(`Guarda casco: Sí${reg.helmetFee?` · ${money(reg.helmetFee)}`:''}`);if(reg.bathroomSelected)extra.push(`Uso de baño: Sí${reg.bathroomFee?` · ${money(reg.bathroomFee)}`:''}`);if(extra.length){if(liq)d.liquidacion=(d.liquidacion?d.liquidacion+'\n':'')+extra.map(x=>'· '+x).join('\n');else d.tarifa=(d.tarifa?d.tarifa+'\n':'')+extra.join('\n')}return d};
const baseCard=tarjetaAuto;tarjetaAuto=function(i){let h=baseCard(i),tags=[];if(i.helmetSelected)tags.push('🪖 Casco');if(i.bathroomSelected)tags.push('🚻 Baño');if(i.obs)tags.push('Obs: '+esc(i.obs));if(tags.length)h=h.replace('</div></div>','<div class="meta">'+tags.join(' · ')+'</div></div></div>');return h};
let q=false;function reconcile(){q=false;try{mountSettings();mountEntry()}catch(e){console.error('PARKOPS v1.6.5',e)}}function schedule(){if(q)return;q=true;setTimeout(reconcile,0)}function init(){ensure();reconcile();const mo=new MutationObserver(schedule);mo.observe(document.body||document.documentElement,{childList:true,subtree:true});window.Parkops165={version:V,reconcile,config:()=>cfg.services}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();