(()=>{
'use strict';
const V='1.6.5',CFGKEY='parkops.admin.config.v2',MODES={minutos:'POR MINUTOS',dia:'TARIFA PLENA DÍA',noche:'TARIFA PLENA NOCHE',cortesia:'CORTESÍA · SIN COBRO'};
function extrasCfg(){try{const c=JSON.parse(localStorage.getItem(CFGKEY)||'{}');return{vatPercent:+c.vatPercent||0,helmetFee:+c.helmetFee||0,bathroomFee:+c.bathroomFee||0}}catch{return{vatPercent:0,helmetFee:0,bathroomFee:0}}}
function toast(m,t='ok'){if(typeof avisar==='function')avisar(m,t)}
function normSpace(v){return String(v||'').trim().toUpperCase().replace(/\s+/g,' ')}
function busy(space){const s=normSpace(space);return ingresos.find(r=>r.occupiesSlot!==false&&!r.salida&&normSpace(r.parkingSpace)===s)}
function installEntryPanel(){const placa=document.getElementById('inPlaca');if(!placa)return;document.getElementById('entryExtra162')?.remove();document.getElementById('entryExtra163')?.remove();const host=placa.closest('.campo')||placa.parentElement;if(!host)return;const x=document.createElement('section');x.id='entryExtra163';x.className='tarjeta';x.style.cssText='margin:12px 0;border:2px solid #2f81f7;padding:14px;border-radius:14px';x.innerHTML=`<h3 style="margin:0 0 12px">ASIGNACIÓN Y TARIFA DEL INGRESO</h3><div class="campo"><label><b>N.º DE PARQUEADERO / ESPACIO *</b></label><input id="parkingSpace163" autocomplete="off" placeholder="Ej. 114, 235, M-12" style="font-size:18px"><div id="spaceStatus163" class="nota">Digite el espacio físico que ocupará.</div></div><div class="campo"><label><b>¿CÓMO SE COBRA ESTE INGRESO?</b></label><select id="tariffMode163" style="width:100%;padding:13px;font-size:16px;border-radius:10px"><option value="minutos">POR MINUTOS</option><option value="dia">TARIFA PLENA · TODO EL DÍA</option><option value="noche">TARIFA PLENA · TODA LA NOCHE</option><option value="cortesia">CORTESÍA · SIN COBRO</option></select><div id="tariffHelp163" class="nota">El valor se calculará por permanencia.</div></div><label style="display:flex;gap:10px;align-items:center;padding:12px;border:1px solid var(--linea);border-radius:10px"><input id="courtesy163" type="checkbox" style="width:22px;height:22px"><span><b>MARCAR COMO CORTESÍA</b><br><span class="nota">Ocupa un espacio y cuenta en la ocupación, pero nunca genera cobro.</span></span></label><div style="display:grid;gap:8px;margin-top:10px"><label style="display:flex;gap:10px;align-items:center;padding:10px;border:1px solid var(--linea);border-radius:10px"><input id="helmet163" type="checkbox" style="width:22px;height:22px"><span><b>DEJA / GUARDA CASCO</b><br><span class="nota">Se cobra el valor configurado solo si se marca.</span></span></label><label style="display:flex;gap:10px;align-items:center;padding:10px;border:1px solid var(--linea);border-radius:10px"><input id="bathroom163" type="checkbox" style="width:22px;height:22px"><span><b>USO DE BAÑO</b><br><span class="nota">Se cobra el valor configurado solo si se marca.</span></span></label></div><div class="campo" style="margin-top:10px"><label><b>OBSERVACIONES</b> <span class="nota">(opcional)</span></label><textarea id="observations163" maxlength="500" placeholder="Ej. deja llaves, recoge familiar, conductor externo, novedad del vehículo..." style="width:100%;box-sizing:border-box;padding:10px;min-height:78px;border-radius:10px"></textarea></div><div class="campo" id="courtesyReasonWrap163" style="display:none;margin-top:10px"><label>Motivo / persona autorizada</label><input id="courtesyReason163" placeholder="Ej. Administrador, operario, cortesía autorizada"></div>`;host.insertAdjacentElement('afterend',x);
const inp=x.querySelector('#parkingSpace163'),st=x.querySelector('#spaceStatus163'),sel=x.querySelector('#tariffMode163'),ck=x.querySelector('#courtesy163'),rw=x.querySelector('#courtesyReasonWrap163'),help=x.querySelector('#tariffHelp163');
const check=()=>{const s=normSpace(inp.value),r=s?busy(s):null;st.textContent=!s?'Digite el espacio físico que ocupará.':r?`OCUPADO por ${r.placa||'otro ingreso'} · NO SE PUEDE ASIGNAR`:`DISPONIBLE · ${s}`;st.style.fontWeight='800';st.style.color=r?'#ff6b6b':s?'#4ade80':''};
const mode=()=>{const courtesy=ck.checked||sel.value==='cortesia';ck.checked=courtesy;if(courtesy)sel.value='cortesia';rw.style.display=courtesy?'block':'none';help.textContent=courtesy?'SIN COBRO · sí ocupa cupo hasta marcar salida':sel.value==='minutos'?'Cobro según tiempo de permanencia':sel.value==='dia'?'Se aplicará la tarifa plena de día':'Se aplicará la tarifa plena de noche'};
inp.addEventListener('input',check);sel.addEventListener('change',mode);ck.addEventListener('change',()=>{if(ck.checked)sel.value='cortesia';else if(sel.value==='cortesia')sel.value='minutos';mode()});mode()}
const oldRegister=registrarEntrada;registrarEntrada=function(enviar){if(!document.getElementById('entryExtra163'))installEntryPanel();const inp=document.getElementById('parkingSpace163'),sel=document.getElementById('tariffMode163'),ck=document.getElementById('courtesy163');if(!inp||!sel)return oldRegister(enviar);const space=normSpace(inp.value),courtesy=ck.checked||sel.value==='cortesia',mode=courtesy?'cortesia':sel.value;if(!space){toast('Debes asignar el N.º de parqueadero antes de registrar','err');inp.focus();return}const r=busy(space);if(r){toast(`El parqueadero ${space} está ocupado por ${r.placa||'otro ingreso'}`,'err');inp.focus();return}const before=new Set(ingresos.map(r=>r.id));oldRegister(enviar);const reg=ingresos.find(r=>!before.has(r.id));if(!reg)return;reg.parkingSpace=space;reg.tariffMode=mode;reg.tariffModeLabel=MODES[mode];reg.isCourtesy=courtesy;reg.courtesyReason=courtesy?(document.getElementById('courtesyReason163')?.value.trim()||'Cortesía'):'';reg.occupiesSlot=true;const ec=extrasCfg();reg.helmetSelected=!!document.getElementById('helmet163')?.checked;reg.bathroomSelected=!!document.getElementById('bathroom163')?.checked;reg.helmetFee=reg.helmetSelected?ec.helmetFee:0;reg.bathroomFee=reg.bathroomSelected?ec.bathroomFee:0;reg.vatPercent=ec.vatPercent;reg.observations=(document.getElementById('observations163')?.value||'').trim();if(courtesy){reg.valor=0;reg.valorParqueo=0;reg.valorRecarga=0}if(typeof sIng==='function')sIng();toast(`Ingreso ${reg.placa} · ${space} · ${MODES[mode]}`,'ok');installEntryPanel();if(typeof refrescar==='function')refrescar()};
const oldReceipt=datosRecibo;datosRecibo=function(reg,liq){const d=oldReceipt(reg,liq);d.parqueadero=reg.parkingSpace||'—';d.modalidad=MODES[reg.tariffMode]||'POR MINUTOS';d.cortesia=reg.isCourtesy?'SÍ · SIN COBRO':'NO';d.observaciones=reg.observations||'';d.guardaCasco=reg.helmetSelected?reg.helmetFee:0;d.usoBano=reg.bathroomSelected?reg.bathroomFee:0;d.ivaPorcentaje=reg.vatPercent||0;if(reg.isCourtesy){d.total='$ 0';d.valor='$ 0';d.parqueo='$ 0';d.recarga='$ 0';d.modalidad=`CORTESÍA · SIN COBRO${reg.courtesyReason?' · '+reg.courtesyReason:''}`}d.vehiculo=`${d.vehiculo} · Puesto ${d.parqueadero} · ${d.modalidad}`;return d};
const oldLiquidar=liquidar;liquidar=function(entrada,fin,tipo,placa,electrico,kwh){const reg=ingresos.find(r=>r.placa===placa&&!r.salida);if(reg?.isCourtesy){const min=Math.max(0,Math.ceil((fin-entrada)/60000));return{total:0,parqueo:0,recarga:0,min,lineas:[`CORTESÍA · SIN COBRO${reg.courtesyReason?' · '+reg.courtesyReason:''}`],mens:false,cortesia:true}}return oldLiquidar(entrada,fin,tipo,placa,electrico,kwh)};
const oldCard=tarjetaAuto;tarjetaAuto=function(i){const raw=oldCard(i),badge=`<span class="chip" style="margin-left:5px">Puesto ${i.parkingSpace||'—'}</span><span class="chip" style="margin-left:5px;${i.isCourtesy?'background:#22c55e;color:#08130b;font-weight:800':''}">${i.isCourtesy?'CORTESÍA · $0':(MODES[i.tariffMode]||'POR MINUTOS')}</span>`;return raw.replace('</div></div>',`${badge}</div></div>`)};
const oldShow=mostrarLiquidacion;mostrarLiquidacion=function(id,simMin){oldShow(id,simMin);const reg=ingresos.find(r=>r.id===id),panel=document.getElementById('panelLiq');if(!reg||!panel)return;if(reg.isCourtesy){const tot=panel.querySelector('.tot');if(tot)tot.textContent=typeof pesos==='function'?pesos(0):'$ 0';const det=panel.querySelector('.det');if(det)det.innerHTML=`· <b>CORTESÍA · SIN COBRO</b><br>· ${reg.courtesyReason||'Cortesía autorizada'}<br>· Parqueadero ${reg.parkingSpace||'—'} continúa ocupado hasta marcar salida`;const medio=panel.querySelector('#medioPago');if(medio){medio.disabled=true;medio.title='Las cortesías no requieren medio de pago'}}};
function init(){installEntryPanel();const mo=new MutationObserver(()=>{if(document.getElementById('inPlaca')&&!document.getElementById('entryExtra163'))installEntryPanel()});mo.observe(document.documentElement,{childList:true,subtree:true});window.ParkopsEntry163={version:V,modes:MODES,busy}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();