(()=>{
'use strict';
const V='1.6.1',TYPES=['carro','moto','bicicleta','patineta'];
const LABEL={carro:'Carros',moto:'Motos',bicicleta:'Bicicletas',patineta:'Patinetas'};
function esc161(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function saveCfg(){if(typeof sCfg==='function')sCfg();if(typeof refrescar==='function')refrescar();}
function toast161(msg,type='ok'){if(typeof avisar==='function')avisar(msg,type);}
function validUrl161(u){if(!u)return false;try{const x=new URL(u);return x.protocol==='https:'||x.protocol==='http:'}catch{return false}}
function ensure(){if(typeof cfg==='undefined')return false;cfg.capacity=Object.assign({enabled:false,carro:0,moto:0,bicicleta:0,patineta:0},cfg.capacity||{});cfg.billing=Object.assign({enabled:false,provider:'',url:'',buttonText:'FACTURA ELECTRÓNICA',mode:'external_url'},cfg.billing||{});return true;}
function capCard(t){const value=Math.max(0,+cfg.capacity[t]||0);return `<div class="parkops-config-card" style="border:1px solid var(--linea);border-radius:14px;padding:14px;background:var(--tarjeta,#1c2128)"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px"><div><b>${LABEL[t]}</b><div class="nota">Capacidad máxima disponible para ${LABEL[t].toLowerCase()}.</div></div><input data-cap161="${t}" type="number" inputmode="numeric" min="0" step="1" value="${value}" style="width:100px;padding:10px;border-radius:9px"></div></div>`;}
function render(){if(!ensure())return;const view=document.getElementById('v-ajustes');if(!view)return;document.getElementById('parkops-capacity-settings')?.remove();document.getElementById('parkops-config161')?.remove();const wrap=document.createElement('div');wrap.id='parkops-config161';wrap.innerHTML=`<details class="acordeon" open><summary>Capacidad por tipo de vehículo</summary><div class="cuerpo"><label class="switch"><input id="capEnabled161" type="checkbox" ${cfg.capacity.enabled?'checked':''}><span class="txt">Habilitar control de capacidad</span></label><p class="nota">Configura cada objeto de forma independiente. Funciona como una configuración operativa: puedes activar el control y definir los cupos de cada tipo.</p><div style="display:grid;gap:10px;margin:12px 0">${TYPES.map(capCard).join('')}</div><button class="btn" id="btnCap161">GUARDAR CAPACIDADES</button></div></details><details class="acordeon"><summary>Facturación electrónica</summary><div class="cuerpo"><label class="switch"><input id="billEnabled161" type="checkbox" ${cfg.billing.enabled?'checked':''}><span class="txt">Habilitar botón de factura electrónica</span></label><div class="campo"><label>Proveedor</label><input id="billProvider161" value="${esc161(cfg.billing.provider||'')}" placeholder="Ej. Siigo, Alegra, proveedor propio"></div><div class="campo"><label>URL del facturador</label><input id="billUrl161" type="url" value="${esc161(cfg.billing.url||'')}" placeholder="https://..."></div><div class="campo"><label>Texto del botón</label><input id="billText161" value="${esc161(cfg.billing.buttonText||'FACTURA ELECTRÓNICA')}"></div><button class="btn" id="btnBill161">GUARDAR FACTURACIÓN</button></div></details>`;view.appendChild(wrap);
wrap.querySelector('#btnCap161').onclick=()=>{cfg.capacity.enabled=wrap.querySelector('#capEnabled161').checked;wrap.querySelectorAll('[data-cap161]').forEach(i=>cfg.capacity[i.dataset.cap161]=Math.max(0,Math.floor(+i.value||0)));saveCfg();toast161('Capacidades guardadas correctamente');};
wrap.querySelector('#btnBill161').onclick=()=>{const enabled=wrap.querySelector('#billEnabled161').checked,url=wrap.querySelector('#billUrl161').value.trim();if(enabled&&!validUrl161(url)){toast161('URL de facturación inválida. Debe iniciar por https:// o http://','err');return}cfg.billing={enabled,provider:wrap.querySelector('#billProvider161').value.trim(),url,buttonText:wrap.querySelector('#billText161').value.trim()||'FACTURA ELECTRÓNICA',mode:'external_url'};saveCfg();toast161('Facturación electrónica guardada');};
}
function init(){if(!ensure())return;render();const mo=new MutationObserver(()=>{if(!document.getElementById('parkops-config161'))render()});mo.observe(document.documentElement,{childList:true,subtree:true});window.ParkopsSettings161={version:V,render};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();