(()=>{'use strict';
const KEY='pqe_v164_pro',ADMINKEY='parkops.admin.config.v2';
const DEFAULTS={exit:{h1:0,h2:0,h3:0,h4:0,day:0},branding:{logo:'',enabled:false}};
const load=()=>{try{return Object.assign({},DEFAULTS,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return structuredClone(DEFAULTS)}};
let pro=load();pro.exit=Object.assign({},DEFAULTS.exit,pro.exit||{});pro.branding=Object.assign({},DEFAULTS.branding,pro.branding||{});
const save=()=>localStorage.setItem(KEY,JSON.stringify(pro));
const money=n=>typeof pesos==='function'?pesos(+n||0):'$ '+Math.round(+n||0).toLocaleString('es-CO');
function toast(m,t='ok'){if(typeof avisar==='function')avisar(m,t)}
function applyLogo(){document.querySelectorAll('.parkops-client-logo').forEach(x=>x.remove());if(!pro.branding.enabled||!pro.branding.logo)return;const header=document.querySelector('header,.topbar,.encabezado,.brand')||document.body.firstElementChild;if(!header)return;const img=document.createElement('img');img.className='parkops-client-logo';img.src=pro.branding.logo;img.alt='Logo del parqueadero';img.style.cssText='display:block;max-width:150px;max-height:58px;object-fit:contain;margin:6px auto;pointer-events:none';header.appendChild(img)}
function mountSettings(){const view=document.getElementById('v-ajustes');if(!view||document.getElementById('proSettings164'))return;const d=document.createElement('details');d.id='proSettings164';d.className='acordeon';d.innerHTML=`<summary>Tarifas rápidas de salida y logo del cliente</summary><div class="cuerpo"><h3>TARIFAS · Servicios adicionales e IVA</h3><p class="nota">Estos valores se aplican únicamente cuando el servicio se selecciona en Registrar ingreso. IVA puede quedar en 0%.</p><div class="fila"><div class="campo"><label>Guarda casco (COP)</label><input id="helmetFee165" type="number" min="0" step="100" inputmode="numeric"></div><div class="campo"><label>Uso de baño (COP)</label><input id="bathroomFee165" type="number" min="0" step="100" inputmode="numeric"></div><div class="campo"><label>IVA (%)</label><input id="vatPercent165" type="number" min="0" max="100" step="0.01" inputmode="decimal"></div></div><button class="btn" id="saveServices165">GUARDAR SERVICIOS E IVA</button><hr style="border:0;border-top:1px solid var(--linea);margin:18px 0"><h3>Botones rápidos de liquidación</h3><p class="nota">Configura el valor que aplicará cada botón en la salida. Un valor 0 conserva el cálculo normal para esa opción.</p><div class="fila">${[['h1','1 HORA'],['h2','2 HORAS'],['h3','3 HORAS'],['h4','4 HORAS'],['day','TODO EL DÍA']].map(([k,l])=>`<div class="campo"><label>${l}</label><input type="number" min="0" step="100" inputmode="numeric" data-exit-rate="${k}" value="${+pro.exit[k]||0}"></div>`).join('')}</div><button class="btn" id="saveExitRates164">GUARDAR TARIFAS DE SALIDA</button><hr style="border:0;border-top:1px solid var(--linea);margin:18px 0"><h3>Logo personalizado del cliente</h3><label class="switch"><input id="logoEnabled164" type="checkbox" ${pro.branding.enabled?'checked':''}><span class="txt">Mostrar logo personalizado en PARKOPS</span></label><div class="campo"><label>Adjuntar logo (PNG, JPG, WEBP o GIF)</label><input id="logoFile164" type="file" accept="image/png,image/jpeg,image/webp,image/gif"></div><div id="logoPreview164" style="min-height:50px;padding:8px;border:1px dashed var(--linea);border-radius:10px;text-align:center">${pro.branding.logo?`<img src="${pro.branding.logo}" style="max-width:180px;max-height:80px;object-fit:contain">`:'Sin logo cargado'}</div><div style="display:flex;gap:8px;margin-top:10px"><button class="btn" id="saveLogo164">GUARDAR LOGO</button><button class="btn sec" id="removeLogo164">QUITAR LOGO</button></div><p class="nota">El logo se guarda localmente dentro de la configuración de este dispositivo y no reemplaza la marca técnica ni la licencia de SOLVEX.</p></div>`;view.appendChild(d);
let ac={};try{ac=JSON.parse(localStorage.getItem(ADMINKEY)||'{}')}catch{};d.querySelector('#helmetFee165').value=Math.max(0,+ac.helmetFee||0);d.querySelector('#bathroomFee165').value=Math.max(0,+ac.bathroomFee||0);d.querySelector('#vatPercent165').value=Math.max(0,+ac.vatPercent||0);d.querySelector('#saveServices165').onclick=()=>{let n={};try{n=JSON.parse(localStorage.getItem(ADMINKEY)||'{}')}catch{}n.helmetFee=Math.max(0,+d.querySelector('#helmetFee165').value||0);n.bathroomFee=Math.max(0,+d.querySelector('#bathroomFee165').value||0);n.vatPercent=Math.min(100,Math.max(0,+d.querySelector('#vatPercent165').value||0));localStorage.setItem(ADMINKEY,JSON.stringify(n));toast('Servicios e IVA guardados','ok')};d.querySelector('#saveExitRates164').onclick=()=>{d.querySelectorAll('[data-exit-rate]').forEach(i=>pro.exit[i.dataset.exitRate]=Math.max(0,+i.value||0));save();toast('Tarifas rápidas de salida guardadas','ok')};
let pending=pro.branding.logo;const file=d.querySelector('#logoFile164');file.onchange=()=>{const f=file.files?.[0];if(!f)return;if(f.size>1024*1024){toast('El logo debe pesar máximo 1 MB','err');file.value='';return}const r=new FileReader();r.onload=()=>{pending=String(r.result||'');d.querySelector('#logoPreview164').innerHTML=`<img src="${pending}" style="max-width:180px;max-height:80px;object-fit:contain">`};r.readAsDataURL(f)};
d.querySelector('#saveLogo164').onclick=()=>{pro.branding.enabled=d.querySelector('#logoEnabled164').checked;pro.branding.logo=pending||'';save();applyLogo();toast('Logo personalizado guardado','ok')};d.querySelector('#removeLogo164').onclick=()=>{pro.branding={logo:'',enabled:false};pending='';save();d.querySelector('#logoEnabled164').checked=false;d.querySelector('#logoPreview164').textContent='Sin logo cargado';applyLogo();toast('Logo personalizado retirado','ok')}}
function optionValue(key,reg){if(key==='monthly')return 0;const v=+pro.exit[key]||0;if(v>0)return v;if(key==='h1'||key==='h2'||key==='h3'||key==='h4'){const hrs=+key.slice(1),fin=reg.entrada+hrs*3600000;try{return +liquidar(reg.entrada,fin,reg.tipo,reg.placa,reg.electrico,reg.kwh||0).total||0}catch{return 0}}if(key==='day'){try{return +liquidar(reg.entrada,Date.now(),reg.tipo,reg.placa,reg.electrico,reg.kwh||0).total||0}catch{return 0}}return 0}
function mountExitButtons(id){const reg=ingresos.find(x=>x.id===id);const panel=document.getElementById('panelLiq'),card=panel?.querySelector('.tarjeta');if(!reg||!card||reg.status==='LIQUIDADO')return;card.querySelector('#quickExit164')?.remove();const box=document.createElement('div');box.id='quickExit164';box.style.cssText='margin:14px 0;padding:12px;border:2px solid var(--ambar);border-radius:12px';const realMin=Math.max(1,Math.ceil((Date.now()-reg.entrada)/60000));const realH=(realMin/60).toFixed(2);box.innerHTML=`<b>SELECCIÓN DE LIQUIDACIÓN</b><div class="nota" style="margin:5px 0 10px">Permanencia real: <b>${realH} h</b> (${realMin} min). Selecciona la modalidad a aplicar.</div><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px">${[['h1','1 HORA'],['h2','2 HORAS'],['h3','3 HORAS'],['h4','4 HORAS'],['day','TODO EL DÍA'],['monthly','MENSUALIDAD']].map(([k,l])=>`<button type="button" class="btn sec" data-qexit="${k}" style="pointer-events:auto">${l}${k!=='monthly'?`<br><small>${money(optionValue(k,reg))}</small>`:''}</button>`).join('')}</div><div id="quickExitSelected164" class="nota" style="margin-top:9px">Sin ajuste manual: se conserva el cálculo real.</div>`;card.insertBefore(box,card.firstChild);
box.querySelectorAll('[data-qexit]').forEach(b=>b.onclick=()=>{const k=b.dataset.qexit;if(k==='monthly'&&!reg.isMonthly){toast('Este ingreso no fue registrado como mensualidad','err');return}reg.exitPricingMode=k;reg.exitPricingLabel=b.textContent.trim().replace(/\s+/g,' ');reg.exitPricingAmount=optionValue(k,reg);if(k==='monthly')reg.exitPricingAmount=0;if(typeof sIng==='function')sIng();box.querySelectorAll('[data-qexit]').forEach(x=>x.style.outline='');b.style.outline='3px solid var(--verde)';box.querySelector('#quickExitSelected164').innerHTML=`Aplicar: <b>${reg.exitPricingLabel}</b>${k==='monthly'?' · SIN COBRO':` · ${money(reg.exitPricingAmount)}`}`;toast(`Modalidad de salida: ${reg.exitPricingLabel}`,'ok')})}
const baseLiquidar=liquidar;liquidar=function(entrada,fin,tipo,placa,electrico,kwh){const out=baseLiquidar(entrada,fin,tipo,placa,electrico,kwh),reg=ingresos.find(x=>x.placa===placa&&!x.salida);if(!reg?.exitPricingMode)return out;if(reg.exitPricingMode==='monthly'||reg.isCourtesy){out.parqueo=0;out.valorParqueo=0;out.total=(+out.recarga||+out.valorRecarga||0);out.lineas=[...(out.lineas||[]),reg.exitPricingMode==='monthly'?'MENSUALIDAD · SIN COBRO DE PARQUEO':'CORTESÍA · SIN COBRO'];return out}const amount=Math.max(0,+reg.exitPricingAmount||0),rec=+out.recarga||+out.valorRecarga||0;out.parqueo=amount;out.valorParqueo=amount;out.total=amount+rec;out.lineas=[...(out.lineas||[]),`Tarifa seleccionada: ${reg.exitPricingLabel||reg.exitPricingMode} · ${money(amount)}`];return out};
const baseShow=mostrarLiquidacion;mostrarLiquidacion=function(id,simMin){baseShow(id,simMin);mountExitButtons(id)};
let queued=false;function reconcile(){queued=false;try{mountSettings();applyLogo()}catch(e){console.error('PARKOPS v1.6.4 PRO',e)}}function schedule(){if(queued)return;queued=true;setTimeout(reconcile,0)}function init(){reconcile();const mo=new MutationObserver(ms=>{if(ms.some(m=>[...m.addedNodes].some(n=>n.nodeType===1&&(n.id==='v-ajustes'||n.querySelector?.('#v-ajustes')))))schedule()});mo.observe(document.body||document.documentElement,{childList:true,subtree:true});window.Parkops164Pro={version:'1.6.4',config:()=>pro,reconcile}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();