(()=>{
'use strict';
const CFG='parkops.v15.config', QUEUE='parkops.v15.pendingReceipts';
const defaults={breb:{enabled:true,keyType:'',keyValue:'',holder:''}};
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const cfg=()=>Object.assign({},defaults,read(CFG,defaults));
const saveCfg=v=>write(CFG,v);
const queue=()=>read(QUEUE,[]);
const saveQueue=v=>write(QUEUE,v);
const online=()=>navigator.onLine!==false;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const brebIcon=`<span aria-label="Bre-B" style="display:inline-grid;place-items:center;width:30px;height:30px;border-radius:9px;background:#111827;color:#fff;font-weight:900;font-size:15px">B<span style="font-size:9px">🔑</span></span>`;
function toast(msg){let e=document.getElementById('parkops-v15-toast');if(!e){e=document.createElement('div');e.id='parkops-v15-toast';e.style.cssText='position:fixed;left:50%;bottom:82px;transform:translateX(-50%);z-index:2147483647;background:#111827;color:#fff;padding:12px 16px;border-radius:12px;box-shadow:0 8px 30px #0005;max-width:90%;font:600 14px system-ui';document.body.appendChild(e)}e.textContent=msg;e.style.display='block';clearTimeout(e._t);e._t=setTimeout(()=>e.style.display='none',3500)}
function setStatus(){let b=document.getElementById('parkops-net-status');if(!b){b=document.createElement('button');b.id='parkops-net-status';b.style.cssText='position:fixed;left:12px;bottom:12px;z-index:2147483645;border:0;border-radius:999px;padding:9px 13px;color:white;font:700 12px system-ui;box-shadow:0 5px 20px #0004';b.onclick=openPending;document.body.appendChild(b)}const n=queue().length;b.textContent=online()?`● EN LÍNEA${n?` · ${n} recibo(s) pendiente(s)`:''}`:`● CONTINGENCIA OFFLINE${n?` · ${n} pendiente(s)`:''}`;b.style.background=online()?'#15803d':'#b45309'}
function enqueueWhatsApp(url){const q=queue();q.push({id:Date.now()+'-'+Math.random().toString(36).slice(2),url,createdAt:new Date().toISOString()});saveQueue(q);setStatus();toast('Sin conexión: operación conservada. El recibo quedó pendiente para WhatsApp.');}
const originalOpen=window.open.bind(window);
window.open=function(url,...args){const u=String(url||'');if(/^https?:\/\/(wa\.me|api\.whatsapp\.com)\//i.test(u)&&!online()){enqueueWhatsApp(u);return null}return originalOpen(url,...args)};
function openPending(){const q=queue();document.getElementById('parkops-pending-modal')?.remove();const d=document.createElement('div');d.id='parkops-pending-modal';d.style.cssText='position:fixed;inset:0;background:#0009;z-index:2147483646;display:grid;place-items:center;padding:16px;font-family:system-ui';d.innerHTML=`<div style="background:#fff;color:#111827;border-radius:16px;padding:20px;width:min(620px,100%);max-height:88vh;overflow:auto"><h2 style="margin-top:0">${online()?'Conexión disponible':'Modo contingencia'}</h2><p>${online()?'Los datos locales están disponibles. Puedes enviar ahora los recibos pendientes.':'PARKOPS continúa operando y conserva los datos en este dispositivo. Los recibos de WhatsApp se enviarán cuando vuelva la conexión.'}</p><h3>Recibos pendientes: ${q.length}</h3><div id="pq">${q.map((x,i)=>`<div style="padding:10px;border:1px solid #e5e7eb;border-radius:10px;margin:8px 0"><b>Recibo ${i+1}</b><br><small>${esc(new Date(x.createdAt).toLocaleString('es-CO'))}</small>${online()?`<br><button data-send="${esc(x.id)}" style="margin-top:7px;padding:8px 12px">Enviar por WhatsApp</button>`:''}</div>`).join('')||'<p>No hay recibos pendientes.</p>'}</div><button id="pq-close" style="padding:9px 14px">Cerrar</button></div>`;document.body.appendChild(d);d.querySelector('#pq-close').onclick=()=>d.remove();d.querySelectorAll('[data-send]').forEach(b=>b.onclick=()=>{const list=queue(),item=list.find(x=>x.id===b.dataset.send);if(!item)return;originalOpen(item.url,'_blank','noopener');saveQueue(list.filter(x=>x.id!==item.id));d.remove();setStatus();toast('Recibo preparado para enviar por WhatsApp.');});}
function addBrebToControls(){document.querySelectorAll('select').forEach(s=>{const context=((s.name||'')+' '+(s.id||'')+' '+(s.closest('label,div,section,form')?.textContent||'')).toLowerCase();if(!/pago|payment|medio/.test(context))return;if([...s.options].some(o=>/bre-?b/i.test(o.textContent)))return;const o=document.createElement('option');o.value='BRE-B';o.textContent='Bre-B · Llave';s.appendChild(o)});document.querySelectorAll('input[type="text"],textarea').forEach(i=>{if(/medios? de pago/i.test(i.previousElementSibling?.textContent||'')){if(!/bre-?b/i.test(i.value))i.value=(i.value.trim()?i.value.trim()+', ':'')+'BRE-B'}})}
function openBreb(){const c=cfg(),b=c.breb||defaults.breb;document.getElementById('parkops-breb-modal')?.remove();const d=document.createElement('div');d.id='parkops-breb-modal';d.style.cssText='position:fixed;inset:0;background:#0009;z-index:2147483646;display:grid;place-items:center;padding:16px;font-family:system-ui';d.innerHTML=`<div style="background:#fff;color:#111827;border-radius:16px;padding:20px;width:min(560px,100%);max-height:90vh;overflow:auto"><div style="display:flex;align-items:center;gap:10px">${brebIcon}<div><h2 style="margin:0">Bre-B · Llave de pago</h2><small>Configura la llave que recibirá los pagos.</small></div></div><label style="display:block;margin-top:16px">Tipo de llave<select id="breb-type" style="display:block;width:100%;padding:10px;margin-top:5px"><option value="">Seleccionar</option>${['Celular','Cédula','Correo','Código alfanumérico'].map(x=>`<option ${b.keyType===x?'selected':''}>${x}</option>`).join('')}</select></label><label style="display:block;margin-top:12px">Llave Bre-B<input id="breb-key" value="${esc(b.keyValue)}" placeholder="Ingresa la llave" style="display:block;width:100%;box-sizing:border-box;padding:10px;margin-top:5px"></label><label style="display:block;margin-top:12px">Titular / nombre comercial<input id="breb-holder" value="${esc(b.holder)}" placeholder="Nombre que verá el operador" style="display:block;width:100%;box-sizing:border-box;padding:10px;margin-top:5px"></label><p style="font-size:12px;color:#6b7280">La llave se almacena localmente en la configuración de PARKOPS. No se guarda ninguna contraseña bancaria.</p><button id="breb-save" style="padding:10px 15px;background:#111827;color:#fff;border:0;border-radius:9px">Guardar llave</button> <button id="breb-close" style="padding:10px 15px">Cerrar</button></div>`;document.body.appendChild(d);d.querySelector('#breb-close').onclick=()=>d.remove();d.querySelector('#breb-save').onclick=()=>{const n=cfg();n.breb={enabled:true,keyType:d.querySelector('#breb-type').value,keyValue:d.querySelector('#breb-key').value.trim(),holder:d.querySelector('#breb-holder').value.trim()};saveCfg(n);d.remove();toast('Llave Bre-B guardada correctamente.');};}
function brebButton(){if(document.getElementById('parkops-breb-btn'))return;const b=document.createElement('button');b.id='parkops-breb-btn';b.innerHTML=`${brebIcon}<span>Configurar Bre-B</span>`;b.style.cssText='position:fixed;right:12px;bottom:62px;z-index:2147483645;display:flex;align-items:center;gap:8px;background:#fff;color:#111827;border:1px solid #d1d5db;border-radius:999px;padding:7px 12px;font:700 12px system-ui;box-shadow:0 5px 20px #0003';b.onclick=openBreb;document.body.appendChild(b)}
function enhance(){addBrebToControls();setStatus();brebButton()}
window.addEventListener('online',()=>{setStatus();if(queue().length){toast('Conexión recuperada. Hay recibos pendientes para enviar.');setTimeout(openPending,500)}});
window.addEventListener('offline',()=>{setStatus();toast('Modo contingencia activado. PARKOPS seguirá guardando la operación localmente.')});
window.ParkopsContingency={isOnline:online,pending:queue,openPending,configBreb:openBreb,version:'1.5.0'};
const obs=new MutationObserver(()=>addBrebToControls());obs.observe(document.documentElement,{childList:true,subtree:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();
