(()=>{
'use strict';
const V='1.6.2';
const MODES={minutos:'Por minutos',dia:'Tarifa plena todo el día',noche:'Tarifa plena toda la noche'};
function toast(m,t='ok'){if(typeof avisar==='function')avisar(m,t)}
function normSpace(v){return String(v||'').trim().toUpperCase().replace(/\s+/g,' ')}
function occupiedSpace(space,exclude){const s=normSpace(space);return ingresos.find(r=>r.id!==exclude&&r.occupiesSlot!==false&&!r.salida&&normSpace(r.parkingSpace)===s)}
function ensureCfg(){if(typeof cfg==='undefined')return false;cfg.billing=Object.assign({enabled:false,provider:'',url:'',buttonText:'FACTURA ELECTRÓNICA',mode:'external_url'},cfg.billing||{});return true}
function validUrl(u){try{const x=new URL(u);return x.protocol==='https:'||x.protocol==='http:'}catch{return false}}
function addEntryFields(){const placa=document.getElementById('inPlaca');if(!placa||document.getElementById('parkingSpace162'))return;const host=placa.closest('.campo')||placa.parentElement;if(!host)return;const block=document.createElement('div');block.id='entryExtra162';block.innerHTML=`<div class="campo"><label>N.º de parqueadero / espacio físico *</label><input id="parkingSpace162" autocomplete="off" placeholder="Ej. 114, 235, M-12"><div id="spaceStatus162" class="nota">Debe indicar el espacio físico que ocupará.</div></div><div class="campo"><label>Modalidad de tarifa *</label><div style="display:grid;gap:8px"><label><input type="radio" name="tariffMode162" value="minutos" checked> Por minutos</label><label><input type="radio" name="tariffMode162" value="dia"> Tarifa plena todo el día</label><label><input type="radio" name="tariffMode162" value="noche"> Tarifa plena toda la noche</label></div></div>`;host.insertAdjacentElement('afterend',block);const inp=block.querySelector('#parkingSpace162'),st=block.querySelector('#spaceStatus162');const check=()=>{const s=normSpace(inp.value);if(!s){st.textContent='Debe indicar el espacio físico que ocupará.';return}const r=occupiedSpace(s);st.textContent=r?`OCUPADO por ${r.placa||'otro vehículo'} · no puede asignarse`:`DISPONIBLE · ${s}`;st.style.fontWeight='700';st.style.color=r?'#ff6b6b':'#4ade80'};inp.addEventListener('input',check);inp.addEventListener('blur',check)}
const prevRegister=registrarEntrada;registrarEntrada=function(enviar){addEntryFields();const inp=document.getElementById('parkingSpace162');if(!inp)return prevRegister(enviar);const space=normSpace(inp.value),mode=document.querySelector('input[name="tariffMode162"]:checked')?.value||'minutos';if(!space){toast('Debes ingresar el N.º de parqueadero / espacio físico','err');inp.focus();return}const busy=occupiedSpace(space);if(busy){toast(`El parqueadero ${space} está OCUPADO por ${busy.placa||'otro vehículo'}. Debes asignar otro espacio.`,'err');inp.focus();return}const before=new Set(ingresos.map(r=>r.id));prevRegister(enviar);const reg=ingresos.find(r=>!before.has(r.id));if(!reg)return;reg.parkingSpace=space;reg.tariffMode=mode;reg.tariffModeLabel=MODES[mode];reg.occupiesSlot=true;sIng();toast(`Ingreso registrado · Parqueadero ${space} · ${MODES[mode]}`,'ok');inp.value='';document.querySelector('input[name="tariffMode162"][value="minutos"]')?.click();if(typeof refrescar==='function')refrescar()};
const prevReceipt=datosRecibo;datosRecibo=function(reg,liq){const d=prevReceipt(reg,liq);d.parqueadero=reg.parkingSpace||'—';d.modalidadTarifa=reg.tariffModeLabel||MODES[reg.tariffMode]||'Por minutos';d.vehiculo=`${d.vehiculo} · Parqueadero ${d.parqueadero} · ${d.modalidadTarifa}`;return d};
const prevCard=tarjetaAuto;tarjetaAuto=function(i){const raw=prevCard(i),x=`<span class="chip" style="margin-left:5px">Puesto ${i.parkingSpace||'—'}</span><span class="chip" style="margin-left:5px">${MODES[i.tariffMode]||'Por minutos'}</span>`;return raw.replace('</div></div>',`${x}</div></div>`)};
function billingButton(card,reg){if(!ensureCfg()||!cfg.billing.enabled||!validUrl(cfg.billing.url)||card.querySelector('#btnFacturaElectronica162'))return;const b=document.createElement('button');b.className='btn sec';b.id='btnFacturaElectronica162';b.textContent=cfg.billing.buttonText||'FACTURA ELECTRÓNICA';b.onclick=()=>{if(reg.status!=='LIQUIDADO'&&!reg.salida){toast('Primero debes liquidar la salida antes de facturar','err');return}if(window.AndroidBridge?.openExternalUrl)window.AndroidBridge.openExternalUrl(cfg.billing.url);else location.href=cfg.billing.url};card.appendChild(b)}
const prevShow=mostrarLiquidacion;mostrarLiquidacion=function(id,simMin){prevShow(id,simMin);const reg=ingresos.find(r=>r.id===id),panel=document.getElementById('panelLiq'),card=panel?.querySelector('.tarjeta');if(!reg||!card)return;let info=card.querySelector('#parkingInfo162');if(!info){info=document.createElement('div');info.id='parkingInfo162';info.className='nota';info.style.margin='10px 0';card.appendChild(info)}info.innerHTML=`<b>Parqueadero:</b> ${reg.parkingSpace||'—'} · <b>Tarifa:</b> ${MODES[reg.tariffMode]||'Por minutos'}`;billingButton(card,reg)};
function enhanceBillingSettings(){if(!ensureCfg())return;const view=document.getElementById('v-ajustes');if(!view||document.getElementById('billingNote162'))return;const details=[...view.querySelectorAll('details')].find(x=>x.textContent.includes('Facturación electrónica'));if(!details)return;const body=details.querySelector('.cuerpo')||details;const n=document.createElement('div');n.id='billingNote162';n.className='nota';n.style.margin='10px 0';n.innerHTML='<b>Datos del parqueadero · Facturación electrónica:</b> configura aquí el proveedor y su vínculo. Durante la salida, después de liquidar, el botón FACTURA ELECTRÓNICA abrirá este portal.';body.insertBefore(n,body.firstChild)}
function init(){addEntryFields();enhanceBillingSettings();const mo=new MutationObserver(()=>{addEntryFields();enhanceBillingSettings()});mo.observe(document.documentElement,{childList:true,subtree:true});window.ParkopsPhysicalSpace={version:V,occupiedSpace,normSpace,modes:MODES}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();