(()=>{'use strict';
const V='1.6.4',MODES={minutos:'POR MINUTOS',dia:'TARIFA PLENA DÍA',noche:'TARIFA PLENA NOCHE',mensualidad:'MENSUALIDAD',cortesia:'CORTESÍA · SIN COBRO'};
const $=s=>document.querySelector(s);function toast(m,t='ok'){if(typeof avisar==='function')avisar(m,t)}function norm(v){return String(v||'').trim().toUpperCase().replace(/\s+/g,' ')}
function ensure(){if(typeof cfg==='undefined')return false;cfg.capacity=Object.assign({enabled:false,carro:0,moto:0,bicicleta:0,patineta:0,recarga:0},cfg.capacity||{});return true}
function occupied(space){let s=norm(space);return ingresos.find(r=>!r.salida&&r.occupiesSlot!==false&&norm(r.parkingSpace)===s)}
function monthlyActive(plate){try{return !!mensVigente(norm(plate))}catch{return false}}
function evText(){if(!ensure())return '';const cap=Math.max(0,+cfg.capacity.recarga||0),used=ingresos.filter(r=>!r.salida&&r.occupiesSlot!==false&&r.electrico).length;return `<b>Cupos de recarga eléctrica:</b> ${used} ocupados / ${cap} configurados / <b>${Math.max(cap-used,0)} disponibles</b>`}
function renderEV(){const box=$('#evAvailability164');if(!box)return;const next=evText();if(box.innerHTML!==next)box.innerHTML=next}
function mountEntry(){const plate=$('#placa');if(!plate||$('#entryExtra164'))return;$('#entryExtra162')?.remove();$('#entryExtra163')?.remove();const tipos=$('#tipos'),anchor=tipos||plate.closest('.placa-wrap')||plate.parentElement;if(!anchor)return;const el=document.createElement('div');el.id='entryExtra164';el.className='tarjeta';el.style.cssText='margin:14px 0;padding:14px;border:2px solid var(--ambar);border-radius:14px;position:relative;z-index:1;pointer-events:auto';el.innerHTML=`<h2 style="margin:0 0 12px">Ubicación y modalidad de cobro</h2><div class="campo"><label for="parkingSpace164"><b>N.º DE PARQUEADERO / PUESTO *</b></label><input id="parkingSpace164" type="text" autocomplete="off" placeholder="Ej. 114, 235, M-12" style="font-size:18px;pointer-events:auto"><div id="spaceStatus164" class="nota">Obligatorio. Indique el puesto físico donde queda estacionado.</div></div><div class="campo"><label for="tariffMode164"><b>MODALIDAD DEL INGRESO *</b></label><select id="tariffMode164" style="width:100%;padding:13px;font-size:16px;border-radius:10px;pointer-events:auto"><option value="minutos">POR MINUTOS</option><option value="dia">TARIFA PLENA · TODO EL DÍA</option><option value="noche">TARIFA PLENA · TODA LA NOCHE</option><option value="mensualidad">MENSUALIDAD</option><option value="cortesia">CORTESÍA · SIN COBRO</option></select><div id="modeHelp164" class="nota"></div></div><div class="campo" id="courtesyWrap164" hidden><label>Motivo de cortesía</label><input id="courtesyReason164" placeholder="Administrador, operario, autorización…"></div><div id="evAvailability164" class="nota" style="padding:10px;border:1px solid var(--linea);border-radius:9px"></div>`;anchor.insertAdjacentElement('afterend',el);
const ps=$('#parkingSpace164'),ss=$('#spaceStatus164'),sel=$('#tariffMode164'),help=$('#modeHelp164');function check(){const s=norm(ps.value),r=s&&occupied(s);ss.textContent=!s?'Obligatorio. Indique el puesto físico donde queda estacionado.':r?`OCUPADO por ${r.placa||'otro vehículo'} · no se puede asignar`:`DISPONIBLE · ${s}`;ss.style.color=r?'var(--rojo)':s?'var(--verde)':''}function mode(){const m=sel.value,active=monthlyActive(plate.value),cw=$('#courtesyWrap164');if(cw)cw.hidden=m!=='cortesia';help.textContent=m==='mensualidad'?(active?'Mensualidad activa detectada para esta placa.':'ATENCIÓN: no se detecta mensualidad vigente para esta placa.'):m==='cortesia'?'Sin cobro; sí ocupa un puesto hasta la salida física.':m==='minutos'?'Liquidación por tiempo de permanencia.':m==='dia'?'Aplicar tarifa plena de día.':'Aplicar tarifa plena de noche.';help.style.color=m==='mensualidad'&&!active?'var(--rojo)':'';renderEV()}ps.addEventListener('input',check);sel.addEventListener('change',mode);plate.addEventListener('input',mode);mode()}
function mountEVConfig(){if(!ensure())return;const view=$('#v-ajustes');if(!view||$('#evCapacity164'))return;const capBtn=$('#btnCap161');if(!capBtn)return;const d=document.createElement('div');d.id='evCapacity164';d.className='parkops-config-card';d.style.cssText='border:1px solid var(--linea);border-radius:14px;padding:14px;margin:10px 0';d.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><div><b>Recarga eléctrica</b><div class="nota">Número de puestos físicos habilitados para cargar vehículos eléctricos.</div></div><input id="capRecarga164" type="number" min="0" step="1" inputmode="numeric" value="${Math.max(0,+cfg.capacity.recarga||0)}" style="width:100px;padding:10px"></div>`;capBtn.parentElement.insertBefore(d,capBtn);capBtn.addEventListener('click',()=>{const input=$('#capRecarga164');cfg.capacity.recarga=Math.max(0,Math.floor(+(input?.value)||0));if(typeof sCfg==='function')sCfg();renderEV()},{passive:true})}
const prevRegister=registrarEntrada;registrarEntrada=function(enviar){if(!$('#parkingSpace164'))mountEntry();const ps=$('#parkingSpace164'),sel=$('#tariffMode164');if(!ps||!sel){toast('No se pudo cargar el módulo de ubicación y tarifa','err');return}const space=norm(ps.value),mode=sel.value,plate=norm($('#placa')?.value);if(!space){toast('Ingrese el N.º de parqueadero / puesto','err');ps.focus();return}const occ=occupied(space);if(occ){toast(`El puesto ${space} está ocupado por ${occ.placa}`,'err');ps.focus();return}if(mode==='mensualidad'&&!monthlyActive(plate)){toast('La placa no tiene una mensualidad vigente. Seleccione otra modalidad.','err');sel.focus();return}if($('#chkElectrico')?.checked){ensure();const cap=Math.max(0,+cfg.capacity.recarga||0),used=ingresos.filter(r=>!r.salida&&r.occupiesSlot!==false&&r.electrico).length;if(cap<=0||used>=cap){toast('No hay cupos de recarga eléctrica disponibles','err');return}}
const before=new Set(ingresos.map(r=>r.id));prevRegister(enviar);const reg=ingresos.find(r=>!before.has(r.id));if(!reg)return;reg.parkingSpace=space;reg.tariffMode=mode;reg.tariffModeLabel=MODES[mode];reg.isCourtesy=mode==='cortesia';reg.courtesyReason=reg.isCourtesy?($('#courtesyReason164')?.value.trim()||'Cortesía autorizada'):'';reg.isMonthly=mode==='mensualidad';reg.occupiesSlot=true;if(reg.isCourtesy||reg.isMonthly){reg.valor=0;reg.valorParqueo=0}if(typeof sIng==='function')sIng();toast(`Ingreso ${reg.placa} · Puesto ${space} · ${MODES[mode]}`,'ok');$('#entryExtra164')?.remove();mountEntry();if(typeof refrescar==='function')refrescar()};
const prevLiquidar=liquidar;liquidar=function(entrada,fin,tipo,placa,electrico,kwh){const r=ingresos.find(x=>x.placa===placa&&!x.salida);if(r?.isCourtesy||r?.isMonthly){const min=Math.max(0,Math.ceil((fin-entrada)/60000)),txt=r.isCourtesy?`CORTESÍA · SIN COBRO${r.courtesyReason?' · '+r.courtesyReason:''}`:'MENSUALIDAD · SIN COBRO DE PARQUEO';let rec=0;if(electrico&&kwh&&!r.isCourtesy){try{const base=prevLiquidar(entrada,fin,tipo,placa,electrico,kwh);rec=base.valorRecarga??base.recarga??0}catch{}}return{total:rec,parqueo:0,valorParqueo:0,recarga:rec,valorRecarga:rec,min,lineas:[txt],mens:r.isMonthly,cortesia:r.isCourtesy}}return prevLiquidar(entrada,fin,tipo,placa,electrico,kwh)};
let scheduled=false;function reconcile(){scheduled=false;try{mountEntry();mountEVConfig();renderEV()}catch(e){console.error('PARKOPS v1.6.4 reconcile',e)}}function schedule(){if(scheduled)return;scheduled=true;setTimeout(reconcile,0)}
function init(){if(!ensure())return;reconcile();const mo=new MutationObserver(muts=>{if(muts.some(m=>[...m.addedNodes,...m.removedNodes].some(n=>n.nodeType===1&&((n.id&&['placa','v-ajustes','btnCap161'].includes(n.id))||n.querySelector?.('#placa,#v-ajustes,#btnCap161')))))schedule()});mo.observe(document.body||document.documentElement,{childList:true,subtree:true});window.Parkops164={version:V,occupied,monthlyActive,reconcile}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();